'use strict';

// Plain data module for the Precedent Machine programme roadmap page
// (pages/admin/programme.js). No I/O, no side effects, no
// module dependencies beyond this file. Every task carries both a `scope`
// (the technical statement, in the programme's own vocabulary) and a
// `plainEnglish` line saying what the step actually achieves for a reader
// who does not know that vocabulary -- tests/programme-roadmap.test.js
// requires the second on every task and refuses a copy of the first.
// Every task, gate, control and
// later-feature entry below cites the governed document (and section,
// commit or receipt path) it was derived from, as of the dates given in
// each `sources` array. When the underlying documents change, update this
// module and its header in the same change -- this file is itself subject
// to CLAUDE.md's rule that a stale header is the most authoritative-
// looking lie in a codebase.
//
// Authored against `codex/recover-m7-20260812` at commit
// d1b8805de1badcbe8e5732d1d0ce786067712dbe (2026-09-03), which is also
// BASE_COMMIT below and the `base_commit` written into exported proposals.
//
// Sources read to build this module: docs/core/PLAN.md, DECISIONS.md
// (entries 22, 25, 26), OPERATING-RULES.md (authority boundary),
// GRAVEYARD.md (entries 1, 12, 15, 16), CLAUDE.md, and the working notes
// docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md and
// WORK5-BLOCKED-CANDIDATE-NOT-EXECUTABLE-ON-REAL-TEXT-2026-09-03.md, plus
// the coord/deal-terms and coord/m7-ext coordination branches (PROTOCOL.md,
// PINS.md, outbox/A-0001 through A-0004, inbox/Q-0001, and the four
// coord/m7-ext status files), read via `git show <ref>:<path>` since those
// branches are not merged here.

const BASE_COMMIT = 'd1b8805de1badcbe8e5732d1d0ce786067712dbe';
const AS_OF = '2026-09-03';

// Standing prohibitions through M9 (PLAN.md section 3). Not tasks: nothing
// here is "done" by anyone doing work, they are locks that stay shut until
// their owning stage passes. Rendered as a fixed panel so a reader does not
// have to infer authority from task status alone.
const CONTROLS = Object.freeze([
  { id: 'model-calls', label: 'Model calls', state: 'ZERO', note: 'Deterministic only through M9. A model-proposed shadow experiment needs its own PLAN/Decision exception and separate Ben experiment authority before any call.' },
  { id: 'phase-b-route-calls', label: 'Phase B route calls', state: 'ZERO', note: 'M8 may prepare a deterministic input packet only; no call.' },
  { id: 'product-data-writes', label: 'Product-data writes', state: 'ZERO', note: 'Through M9. Durable writes start at Product Stage 4.' },
  { id: 'selector-changes', label: 'Selector changes', state: 'ZERO', note: 'The extractor selector does not move until M10.' },
  { id: 'pin-changes', label: 'Pin changes', state: 'ZERO' },
  { id: 'baseline-changes', label: 'Baseline changes', state: 'ZERO' },
  { id: 'serving-changes', label: 'Serving changes', state: 'ZERO', note: 'External serving stays disabled through M10 and Product Stages 3-8.' },
  { id: 'publication-authority', label: 'Publication authority', state: 'NONE', note: 'Becomes PUBLIC only under Ben\'s one-use Product Stage 9 production authority.' },
  { id: 'external-serving', label: 'External serving', state: 'DISABLED' },
  { id: 'sealed-m0-m2', label: 'Sealed M0, M1, M2 artefacts', state: 'UNCHANGED' },
  { id: 'production-authority', label: 'Production authority', state: 'NONE', note: 'OPERATING-RULES.md authority boundary: production activation, production data and real credentials stay prohibited regardless of any carve-out below it.' },
].map((c) => Object.freeze({ ...c, sources: Object.freeze(['docs/core/PLAN.md §3 "Current state and authority"', 'docs/core/OPERATING-RULES.md "Exact working location and authority boundary"']) })));

// PLAN.md section 20, "Open Ben rulings" -- the standing register of
// questions only Ben can answer, independent of any one task's status.
const OPEN_BEN_RULINGS = Object.freeze([
  { id: 'obr-1', text: 'For each family and provision subtype, which semantic roles are required before a claim can resolve?', kind: 'legal' },
  { id: 'obr-2', text: 'What exact size and composition should the modest risk-weighted blind sample use before M10?', kind: 'legal' },
  { id: 'obr-3', text: 'For each family calibration pack, which roles must appear in the compact row and which may move to expansion?', kind: 'legal' },
  { id: 'obr-4', text: 'Which proposed no-output dispositions, if any, are legally acceptable?', kind: 'legal' },
  { id: 'obr-5', text: 'After recovery and M7 legal acceptance, does Ben authorise the exact M9 work order?', kind: 'authority', relatedTask: 'm9-certification' },
  { id: 'obr-6', text: 'Does Ben authorise any later Phase B or other model run?', kind: 'authority' },
  { id: 'obr-7', text: 'If M9 passes, does Ben approve the exact M10 selector and named private internal consumers?', kind: 'authority', relatedTask: 'm10-activation' },
  { id: 'obr-8', text: 'What authority applies to hosted staging and production database operations?', kind: 'authority', relatedTask: 'product-stage-9' },
  { id: 'obr-9', text: 'Before external activation, does Ben require login for the live site and has the exposed service key been rotated?', kind: 'authority', relatedTask: 'product-stage-7' },
  { id: 'obr-10', text: 'Does Ben authorise the exact serving, publication and production-cutover packet after the retained product stages pass?', kind: 'authority', relatedTask: 'product-stage-9' },
  { id: 'obr-11', text: 'Must legacy V1 quotation spans be backfilled before V1 retirement?', kind: 'legal', relatedTask: 'product-stage-6' },
  { id: 'obr-12', text: 'May any of the possible 128 legacy database rows be deleted, or must each remain with an alias or retention record?', kind: 'legal', relatedTask: 'product-stage-6' },
].map((r) => Object.freeze({ ...r, sources: Object.freeze(['docs/core/PLAN.md §20 "Open Ben rulings"']) })));

// The re-plan's session-1 decision set (M7-V2-REPLAN §8, answered in
// DECISIONS.md #26 on 2026-09-03) plus the session-2/3/4 items still open.
// Referenced from repair-phase0-authority's benQuestions below by id.
const REPLAN_SESSION1_QUESTIONS = Object.freeze([
  'Q1', 'Q1a', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q18',
]);
const REPLAN_SESSION2_QUESTIONS = Object.freeze(['Q11', 'Q17', 'Q19']);

function estimateKnown(minDays, maxDays, basis) {
  return Object.freeze({ minDays, maxDays, basis, unknownReason: null });
}

function estimateUnknown(reason) {
  return Object.freeze({ minDays: null, maxDays: null, basis: null, unknownReason: reason });
}

const AFTER_FIRST_REAL_RUN_UNKNOWN = 'Dates past the first real ten-agreement run (Phase 1 exit) are not estimated. ' +
  'Producer to consumer, coord/deal-terms outbox/A-0001: "every date past that run is unknown, and I will not invent one." ' +
  'PINS.md pins the same point: "nothing after node 4 has a date."';

const HISTORICAL_NOT_ESTIMATED = 'Completed before the re-plan introduced working-day estimates; no range was recorded for it in the governed documents.';

// One unified task graph. `group` is a display/derivation grouping, not a
// separate graph -- every dependsOn id below must resolve to another id in
// this same array (tests/programme-roadmap.test.js enforces it). `owner`
// is one of 'lead' (the lead/integrator session), 'ext' (the external
// agent, on the channel named by `externalChannel`), 'ben', or 'ci'.
const TASKS = Object.freeze([
  {
    id: 'm0-m4-foundation',
    title: 'M0-M4: architecture, index, context, base analysis',
    plainEnglish: 'The groundwork: teach the system to read a merger agreement — split it into sections, work out who the parties are, resolve the defined terms, and build a first structured picture of the document. Nothing here decides what any provision means.',
    group: 'foundation',
    scope: 'Frozen authority/cohort/baseline/diff contract (M0); INCREMENTAL_RESTRUCTURE decision (M1); seven sealed shadow AgreementIndex files (M2); provenanced context, references, definitions, party topology (M3); base AgreementAnalysis, required-role validator, resolution-set diff (M4).',
    dependsOn: [],
    owner: 'lead',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'M3 sealed by receipts/stage-2y-structure-m3-context-compilation.json; M4 sealed by receipts/stage-2y-structure-m4-agreement-analysis.json; both frozen and unchanged since.',
    sources: ['docs/core/PLAN.md §6 "Stage order"', 'docs/core/PLAN.md §7 "Completed input to the open plan"', 'docs/core/OPERATING-RULES.md "Current narrower rule, 2026-08-14"'],
  },
  {
    id: 'm5-m6-v1-run',
    title: 'M5-M6: family adapters and projection (V1, ran locally)',
    plainEnglish: 'A first attempt at labelling and displaying 1,111 provisions. It ran, but it used rough categories instead of the agreed detailed ones, so the output was never legally accepted.',
    group: 'm7-v1',
    scope: 'M5 correction labelled 1,111 shadow propositions complete; M6 projected 1,111 normal rows. Both bypassed the sealed subtype schemas and accepted coarse role buckets as complete -- not legally accepted output.',
    dependsOn: ['m0-m4-foundation'],
    owner: 'lead',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'Ran; superseded by the M7 V2 repair. Its 1,111 complete labels are not legally accepted (PLAN.md §6 stage-order table).',
    sources: ['docs/core/PLAN.md §3 "Current state and authority"', 'docs/core/PLAN.md §6 "Stage order"'],
  },
  {
    id: 'm7-v1-lawyer-review',
    title: 'M7 (V1): fixed 50-item lawyer review',
    plainEnglish: 'Ben read a fixed 50-item sample of that output: 19 right, 31 wrong. That result is what triggered the entire repair effort below.',
    group: 'm7-v1',
    scope: 'Ben reviewed the fixed 50-item packet: 19 correct, 31 incorrect. Six correct items also carry a substantive missing-law note; one carries a page-number artefact. Only 12 items are clean regression controls.',
    dependsOn: ['m5-m6-v1-run'],
    owner: 'ben',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'Gate result FAILED_RETURN_AFFECTED_ITEM_TYPES_FOR_REPAIR, completed 2026-08-14.',
    sources: ['docs/core/PLAN.md §3 "Current state and authority"', 'docs/core/PLAN.md §12 "M7: corpus verification and legal calibration"'],
  },
  {
    id: 'm7v2-work0-evidence-root',
    title: 'M7 V2 repair Work 0: freeze failure evidence',
    plainEnglish: 'Freeze the evidence of the failure — the sample, the errors, what the system believed at the time — so the repair can be checked against what actually went wrong. It preserves; it repairs nothing.',
    group: 'm7-v2-repair',
    scope: 'Binds the failed review, fixed 50-item sample, 38 repair items, 12 controls, sealed programme rulings, sealed M3/M4 trust roots. Preserves evidence; does not repair or accept M7.',
    dependsOn: ['m7-v1-lawyer-review'],
    owner: 'lead',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: 'evidence/canonical-v2/stage-2y-structure-migration/control/m7-v2-repair-work1-7-authority.json',
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'evidence/canonical-v2/stage-2y-structure-migration/receipts/stage-2y-structure-m7-v2-repair-evidence-root.json (passed).',
    sources: ['docs/core/PLAN.md §3 "Current state and authority"'],
  },
  {
    id: 'm7v2-work1-4-original-candidate',
    title: 'M7 V2 repair Work 1-4 (original): register deterministic candidate 9a3ccbf7',
    plainEnglish: 'Built a replacement extractor and registered it. The process was sound, but every test used made-up documents rather than real agreements.',
    group: 'm7-v2-repair',
    scope: 'Deterministic generator, 1,382 profiles, contract validator, registration. Governance sound; every proof ran only against in-memory fixtures whose base analysis has one claim per node and marker-string source text -- never a real agreement.',
    dependsOn: ['m7v2-work0-evidence-root'],
    owner: 'lead',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: 'evidence/canonical-v2/stage-2y-structure-migration/control/m7-v2-repair-work1-7-authority.json',
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'Registration 9a3ccbf7…; Work 4 correction landed under DECISIONS.md #25 (registration b11388ab, superseded, byte-identical outputs retained).',
    sources: ['docs/core/DECISIONS.md #25 "Work4 candidate correction before Work 5"', 'docs/codex-program/notes/WORK5-BLOCKED-CANDIDATE-NOT-EXECUTABLE-ON-REAL-TEXT-2026-09-03.md "Why the receipts did not catch it"'],
  },
  {
    id: 'm7v2-work5-blocked-finding',
    title: 'Finding: candidate 9a3ccbf7 cannot compile a real agreement',
    plainEnglish: 'The discovery that the replacement could not read a real agreement at all — none of its expected phrases appear in real contract text. All 24 affected provision families were stopped.',
    group: 'm7-v2-repair',
    scope: 'Dry run of consolidateAnalysis on the first fixed-sample agreement fails before producing any rule: one-claim-per-node guard, 1,382 marker-text-only profiles (0 of 1,399 tokens occur in real text), and a generator that compiles only a synthetic first-slice expression signature. Classified FALSE_COMPLETE_FIXTURE for all 24 affected families.',
    dependsOn: ['m7v2-work1-4-original-candidate'],
    owner: 'lead',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'docs/codex-program/notes/WORK5-BLOCKED-CANDIDATE-NOT-EXECUTABLE-ON-REAL-TEXT-2026-09-03.md (finding for Ben, no decision taken; scratch scripts not committed).',
    sources: ['docs/codex-program/notes/WORK5-BLOCKED-CANDIDATE-NOT-EXECUTABLE-ON-REAL-TEXT-2026-09-03.md'],
  },
  {
    id: 'm7v2-replan-adopted',
    title: 'Ben adopts the M7 V2 re-plan, all recommendations',
    plainEnglish: 'Ben approved the plan to fix it, all 19 recommendations. This authorises the work; it does not perform any of it.',
    group: 'm7-v2-repair',
    scope: 'Ben answered all 19 re-plan questions (Q1-Q19) "All recommended". Recorded as DECISIONS.md #26. Authorises drafting the replacement authority; no governed write happens until it is committed and validated.',
    dependsOn: ['m7v2-work5-blocked-finding'],
    owner: 'ben',
    externalChannel: null,
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(HISTORICAL_NOT_ESTIMATED),
    evidence: 'docs/core/DECISIONS.md #26 "M7 V2 re-plan adopted, all recommendations: DECIDED 2026-09-03".',
    sources: ['docs/core/DECISIONS.md #26', 'docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §8'],
  },
  {
    id: 'repair-phase0-authority',
    title: 'Phase 0: draft and seal the replacement authority',
    plainEnglish: 'Write the formal permission slip for the repair: what may change, what must stay untouched, and exactly which files and commands are allowed. This is where the work currently sits.',
    group: 'm7-v2-repair',
    scope: 'One replacement authority, control/m7-v2-repair-contract-candidate-replacement-authority.json, recording the FALSE_COMPLETE_FIXTURE stop, retaining every Work 2-4 output immutable, enumerating every successor manifest/receipt/schema/test path and command, and naming the core-document regions for DECISIONS.md #26, GRAVEYARD.md and CODEBASE-GUIDE.md. This is the current position: the branch head is mid-draft.',
    dependsOn: ['m7v2-replan-adopted'],
    owner: 'lead',
    externalChannel: null,
    status: 'in_progress',
    blockedReason: null,
    waitsOnBen: true,
    benQuestions: REPLAN_SESSION1_QUESTIONS,
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateKnown(1, 2, 'docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §9 "First two weeks", Days 1-2'),
    evidence: 'Planned: control/m7-v2-repair-contract-candidate-replacement-authority.json, validated by the manifest validator (not yet committed). Exit gate per re-plan §5 Phase 0.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 0"', '§9 "First two weeks"', '§10 "Dependency graph to publication" nodes 1-2'],
  },
  {
    id: 'quarantine-preview-path-pr',
    title: 'Quarantine the synthetic preview serving path',
    plainEnglish: 'Wall off a demo screen that displays invented data, so nobody mistakes it for real output. Independent of the repair — it just has to land before the branch merges.',
    group: 'm7-v2-repair',
    scope: 'A product-code PR, outside the repair authority, on Ben\'s direct instruction (re-plan Q9, answered yes in DECISIONS.md #26). Not gated by the repair phases: it can be built and merged in parallel with Phases 0-3, and only needs to land before the recovery branch merges to main.',
    dependsOn: ['m7v2-replan-adopted'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown('No working-day range is stated for this PR in the governed documents; it is a bounded product-code change but no estimate was recorded.'),
    evidence: 'Planned: a merged PR quarantining the synthetic preview serving path, referenced as a merge precondition at re-plan §10 node 12.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §8 Q9', '§10 node 12', 'docs/core/DECISIONS.md #26 "Q9"'],
  },
  {
    id: 'repair-phase1-issue-only-run',
    title: 'Phase 1: ten agreements compile as an issue-only run',
    plainEnglish: 'The first run against ten real agreements. Everything is expected to come back "needs review": the point is proving the pipeline works end to end and reports honestly, not extracting anything usable yet.',
    group: 'm7-v2-repair',
    scope: 'Interim registration; governed occurrence grouping; hash-bound closures with ancestor-context extension; REVIEW_RESIDUE and issue codes; review-only routing; the attempt record; definition-edge projection (rules 1-2). Every occurrence is expected NO_SINGLE_PROFILE, review-only -- this is the first real V2 run, and it proves plumbing and honest routing, not extraction. This is the "first real run" that later dates key off.',
    dependsOn: ['repair-phase0-authority'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on repair-phase0-authority (the replacement authority must be committed and validated first).',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateKnown(8, 12, 'docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §9, Days 3-14 (interim registration through Work 2 successor receipt and Phase 1 exit)'),
    evidence: 'Planned: ten AGREEMENT_ANALYSIS/V2 files passing the false-complete guard, plus the Work 2 successor receipt and a per-Red-Hat-item structural-reachability report.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 1"', '§9', '§10 node 4'],
  },
  {
    id: 'repair-phase2-extraction',
    title: 'Phase 2: extraction, profiles, Ben\'s profile session',
    plainEnglish: 'The real extraction work: teach the system to find and quote actual clauses, and draft roughly 114 provision patterns against real text. Ben\'s heaviest review session sits here.',
    group: 'm7-v2-repair',
    scope: 'Effect ledger; quote locator, parsers and resolver facts; party route and record; ~114 subtype profiles drafted with real hash-bound fixtures; the family regex module; interim registration; a ten-agreement run with a reason-code report. Ben\'s session 2 (the heaviest of his four) rules the signature policy, exclusions, family-wide no-output policies and Termination fixtures, and precedes sealing.',
    dependsOn: ['repair-phase1-issue-only-run'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on Phase 1 exit.',
    waitsOnBen: true,
    benQuestions: REPLAN_SESSION2_QUESTIONS,
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: Work 3 successor receipt binding Ben\'s session-2 record and hash-verified fixtures.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 2"', '§10 node 5-6'],
  },
  {
    id: 'repair-phase3-candidate-registration',
    title: 'Phase 3 setup: Work 4 successor, final registration, verifier',
    plainEnglish: 'Reconcile the output, register the finished extractor, and re-run the verifier. Both remaining work streams depend on this landing.',
    group: 'm7-v2-repair',
    scope: 'Projector reconciliation and view-policy update (Work 4 successor); final candidate registration; verifier rerun. The precondition both Work 5 and Work 6 depend on.',
    dependsOn: ['repair-phase2-extraction'],
    owner: 'lead',
    externalChannel: 'm7-ext',
    status: 'not_started',
    blockedReason: 'Waiting on Phase 2 (profiles and Ben session 2).',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: final candidate registration and verifier rerun receipts.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 3"', '§10 node 7-8'],
  },
  {
    id: 'work5-packet-session3',
    title: 'Work 5: replay the fixed 50, Ben session 3',
    plainEnglish: 'Re-run the original failed 50-item sample through the new system and put it back in front of Ben, new answer beside old.',
    group: 'm7-v2-repair',
    scope: 'Replay the fixed 50 with the V2 packet (old card, enum, verbatim note beside the new result; items 2, 4, 45 afresh; item 39 both trees; item 4 with chapeau; full closures for source-limited decisions). Ben\'s session 3 reviews all 50 plus the 12 controls, plus items 14 and 43 (Q8). Runs in parallel with Work 6.',
    dependsOn: ['repair-phase3-candidate-registration'],
    owner: 'lead',
    externalChannel: 'm7-ext',
    status: 'not_started',
    blockedReason: 'Waiting on the final candidate registration.',
    waitsOnBen: true,
    benQuestions: ['Q8', 'Q14'],
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: rendered Work 5 packet and Ben session-3 record. ext/m7-w5-renderer is currently PARKED pending this precondition (coord/m7-ext status/w5-renderer.md, 2026-09-03: "A-0008 repeats do-not-start").',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 3"', '§10 node 9', 'coord/m7-ext handoffs/m7-ext/status/w5-renderer.md'],
  },
  {
    id: 'work6-rebind-rerun',
    title: 'Work 6: rebind and rerun the nine external reports',
    plainEnglish: 'The outside agent re-runs its nine reports against the final registered extractor. Happens at the same time as the 50-item replay.',
    group: 'm7-v2-repair',
    scope: 'External agent rebinds and reruns the nine Work 6 reports against the final registration. Depends only on repair-phase3-candidate-registration, in parallel with Work 5 -- the clearest current example of parallelisable work once Phase 3 setup lands.',
    dependsOn: ['repair-phase3-candidate-registration'],
    owner: 'ext',
    externalChannel: 'm7-ext',
    status: 'not_started',
    blockedReason: 'Waiting on the final candidate registration.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: nine rebound Work 6 reports. Currently HELD pending this precondition (coord/m7-ext handoffs/m7-ext/status/w6-audit.md, 2026-09-03: "A-0009 deferred review"; PR #486 stays draft).',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 3"', '§10 node 10', 'coord/m7-ext handoffs/m7-ext/status/w6-audit.md'],
  },
  {
    id: 'work7-verify-signoff',
    title: 'Work 7: verifier, adversarial review, Ben session 4, M7 V2 receipt',
    plainEnglish: 'Independent verification, then a fresh adversarial review by someone who did not build it, then Ben\'s sign-off. This is the legal gate: if it passes, the repair is sealed.',
    group: 'm7-v2-repair',
    scope: 'Independent verifier rerun; a fresh-session adversarial review that wrote neither the candidate nor the plan; Ben\'s session 4 sign-off. Any correction from session 3 or the review is batched into one new registration, a full reopen of all 50, and a Work 6 rerun (Q14) -- one such loop is budgeted. On PASS, the M7 V2 repair receipt seals. This is the M7 legal gate for V2.',
    dependsOn: ['work5-packet-session3', 'work6-rebind-rerun'],
    owner: 'ben',
    externalChannel: 'm7-ext',
    status: 'not_started',
    blockedReason: 'Waiting on Work 5 and Work 6.',
    waitsOnBen: true,
    benQuestions: ['Q14'],
    authorityRecord: 'control/m7-v2-repair-contract-candidate-replacement-authority.json',
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: sealed M7 V2 repair receipt, one identical registration ID across Work 5, 6 and 7. ext/m7-w7-verifier already ACCEPTED at 54133f0a for the verifier itself (coord/m7-ext status/w7-verifier.md); this task is the full sign-off using the Phase 3 candidate.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 3"', '§10 node 11', 'coord/m7-ext handoffs/m7-ext/status/w7-verifier.md'],
  },
  {
    id: 'recovery-branch-merge-to-main',
    title: 'Merge recovery branch through codex/stage-2y-structure-m2 to main',
    plainEnglish: 'Merge the repair back into the main line of code, re-running the evidence checks because main will have moved on in the meantime.',
    group: 'm7-v2-repair',
    scope: 'Quarantine PR merged; codex/recover-m7-20260812 merged to codex/stage-2y-structure-m2, then main, with the quarantine test as a precondition; evidence gates re-run because main will have moved.',
    dependsOn: ['work7-verify-signoff', 'quarantine-preview-path-pr'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the sealed M7 V2 repair receipt and the quarantine PR.',
    waitsOnBen: true,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: merge commit on main plus a green evidence-gates re-run.',
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 4"', '§10 node 12'],
  },
  {
    id: 'm9-certification',
    title: 'M9: certify the shadow extractor',
    plainEnglish: 'Certify the extractor: freeze a release candidate, prove it behaves identically on repeated runs, and record a rollback proof. Pre-approved, provided the entry conditions hold exactly.',
    group: 'certification',
    scope: 'Remaining-open-world ledger; frozen release candidate; isolated candidate harness; focused seam checks; run-all-invariants and build once; rehearse current/shadow/current with digests recorded; seal rollback proof and the Stage 2Y certificate. Pre-authorised on exact entry conditions with zero deviation (Decision 22); not a fresh legal decision if those conditions hold exactly.',
    dependsOn: ['recovery-branch-merge-to-main'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the merged, evidence-gated recovery branch.',
    waitsOnBen: true,
    benQuestions: ['Q10'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: shadow/m9/stage-2y-certificate.json (schema STAGE_2Y_CERTIFICATE/V1).',
    sources: ['docs/core/PLAN.md §14 "M9: certify the shadow extractor"', 'docs/core/DECISIONS.md #22'],
  },
  {
    id: 'm10-activation',
    title: 'M10: activate the certified private internal extractor',
    plainEnglish: 'Switch the certified extractor on for named internal users only. Still nothing published and nothing customer-facing.',
    group: 'certification',
    scope: 'Ben signs the exact authority packet; activation certificate binds the M10 authority and M9 certificate; selects the M9-certified extractor for named private internal consumers only. Ends in PRIVATE_INTERNAL_EXTRACTOR_ACTIVE -- not product-ready: publication stays NONE, external serving stays disabled, product writes stay zero.',
    dependsOn: ['m9-certification'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the M9 certificate.',
    waitsOnBen: true,
    benQuestions: ['Q10'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: signed M10 authority packet and activation certificate (schema STAGE_2Y_PRIVATE_INTERNAL_EXTRACTOR_ACTIVE_CERTIFICATE/V1).',
    sources: ['docs/core/PLAN.md §15 "M10: activate the certified private internal extractor"', 'docs/core/DECISIONS.md #22'],
  },
  {
    id: 'product-stage-3',
    title: 'Product Stage 3: finish unresolved semantic and taxonomy work',
    plainEnglish: 'Go through every provision the system still cannot categorise and have Ben rule on each: define it, decide it produces no output, or record it as an open legal question.',
    group: 'product-stage',
    scope: 'Cluster every remaining-open-world member by proposed legal/comparison type; Ben seals semantic-disposition-targets.json and one decision per item (APPROVED_CLAIM_DEFINITION, APPROVED_NO_OUTPUT or OPEN_LEGAL_QUESTION); build the disposition ledger; extend the M6 output-owner registry and view policy; seal a deterministic Stage 3 semantic candidate.',
    dependsOn: ['m10-activation'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the M10 activation certificate.',
    waitsOnBen: true,
    benQuestions: ['obr-1', 'obr-2', 'obr-3', 'obr-4'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: evidence/canonical-v2/product-stage-3/receipt.json (PRODUCT_STAGE_PACKET_RECEIPT/V1).',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 3'],
  },
  {
    id: 'product-stage-4',
    title: 'Product Stage 4: durable validation and import',
    plainEnglish: 'Make loading data into the database dependable — safe to re-run, safe to restart part-way through, and provably restorable from backup.',
    group: 'product-stage',
    scope: 'Harden the import driver; prove idempotency and restart on an approved non-production database; refuse quarantined/unresolved/incomplete propositions; prove backup and restore.',
    dependsOn: ['product-stage-3'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 3 receipt.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-4/receipt.json plus product-stage-4/import-state.json.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 4'],
  },
  {
    id: 'product-stage-5',
    title: 'Product Stage 5: database reader, serving, rendered rows',
    plainEnglish: 'Read the data back out and render a second deal\'s page without anyone hand-writing it. Proof the pipeline actually feeds the product.',
    group: 'product-stage',
    scope: 'Read complete claims/relationships; render a second deal without a hand-written serving file; prove the value through an HTTP response and the real page; roll every serving family through the consolidated output-owner registry.',
    dependsOn: ['product-stage-3', 'product-stage-4'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 3 and Stage 4 receipts.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-5/receipt.json.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 5'],
  },
  {
    id: 'product-stage-6',
    title: 'Product Stage 6: 40-agreement certification corpus',
    plainEnglish: 'Fix the certification corpus at 40 agreements, run all 25 provision families across it, and certify the result.',
    group: 'product-stage',
    scope: 'Freeze product-corpus-manifest.json with exactly 40 unique fully admitted agreement identities; run all 25 families across the manifest; corpus open-world ledger and discovery/revision loop back to Stage 3 as needed; certified-corpus-candidate and corpus-certificate. Certifies the complete product corpus, not only the ten-agreement migration cohort.',
    dependsOn: ['product-stage-3', 'product-stage-4', 'product-stage-5'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 3, 4 and 5 receipts.',
    waitsOnBen: true,
    benQuestions: ['obr-11', 'obr-12'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-6/corpus-certificate.json and certified-corpus-candidate.json, 40 agreements.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 6'],
  },
  {
    id: 'product-stage-7',
    title: 'Product Stage 7: security and operations',
    plainEnglish: 'Security: confirm the live site requires a login, confirm the exposed service key was rotated, and prove the app refuses access from outside. Gates anything customer-facing.',
    group: 'product-stage',
    scope: 'Ben confirms whether the live site requires login and whether the exposed service key was rotated; set auth env vars and prove refusal from outside; re-enable the four contained routes only after hostile tests pass. Gates external product activation.',
    dependsOn: ['product-stage-6'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 6 corpus certificate.',
    waitsOnBen: true,
    benQuestions: ['obr-9'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-7/receipt.json.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 7'],
  },
  {
    id: 'product-stage-8',
    title: 'Product Stage 8: product features (search, comparison, market stats)',
    plainEnglish: 'Build the actual product features — search, deal comparison, market statistics — proved in preview only, with no production authority granted.',
    group: 'product-stage',
    scope: 'Preview-import the certified corpus; enable market statistics with corpus/selected-deal scopes; restore search after load/query guards pass; build the comparison view (no three-deal limit, horizontal scrolling, source-completeness indicators). Passes in preview only; grants no production authority.',
    dependsOn: ['product-stage-5', 'product-stage-6', 'product-stage-7'],
    owner: 'lead',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 5, 6 and 7 receipts.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-8/receipt.json plus preview-import-state.json.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 8'],
  },
  {
    id: 'product-stage-9',
    title: 'Product Stage 9: production cutover and rollback',
    plainEnglish: 'Go live: rehearse on staging, take Ben\'s one-use production authority, load only the certified files, turn serving on family by family, and prove a rollback works.',
    group: 'product-stage',
    scope: 'Named hosted-staging rehearsal; Ben\'s exact one-use production authority; production backup/restore drill; import only the exact Stage 6 certified-corpus files into a dark namespace; enable V2 serving by approved family; smoke tests; one production rollback and move-forward. Capitalisation excluded (PARKED) from this stage\'s mission-ready family set.',
    dependsOn: ['product-stage-3', 'product-stage-4', 'product-stage-5', 'product-stage-6', 'product-stage-7', 'product-stage-8'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on Stages 3 through 8.',
    waitsOnBen: true,
    benQuestions: ['obr-8', 'obr-10'],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-9/production-cutover-receipt.json (the one-use, non-repeatable production authority record).',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 9'],
  },
  {
    id: 'product-stage-9f',
    title: 'Product Stage 9F: Capitalisation',
    plainEnglish: 'Capitalisation is handled on its own, with a separate schema, rehearsal and approval. Stage 9 grants it nothing.',
    group: 'product-stage',
    scope: 'Separate from Stage 9 and grants it no authority. Needs a separate Ben-approved Capitalisation required-role schema and work order, its own staging rehearsal and one-use production authority.',
    dependsOn: ['product-stage-6', 'product-stage-9'],
    owner: 'ben',
    externalChannel: null,
    status: 'not_started',
    blockedReason: 'Waiting on the Stage 6 manifest and the Stage 9 production cutover.',
    waitsOnBen: true,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: product-stage-9f/receipt.json. Until move-forward approval, status stays PARKED, not PASS.',
    sources: ['docs/core/PLAN.md §16 "Product work after M10", Stage 9F'],
  },
  {
    id: 'pkg-contract-draft1',
    title: 'Deal Terms release-package contract, draft 1',
    plainEnglish: 'First version of the data format Precedent Machine hands to the Deal Terms consumer, with a verifier that checks a package against it.',
    group: 'package',
    scope: 'Versioned JSON Schema 2020-12 for the manifest and per-deal document, plus the corpus-manifest input contract, a synthetic one-deal example and a 258-check offline verifier. Every identity rule cites lib/canonical-v2/canonical-bytes.js.',
    dependsOn: [],
    owner: 'ext',
    externalChannel: 'deal-terms',
    status: 'done',
    blockedReason: null,
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown('Delivered same-day as requested; no separate range was given.'),
    evidence: 'docs/codex-program/handoffs/deal-terms/contract/ on coord/deal-terms at commit 17f43368 (divergence note 8dedcaec); example-one-deal-package/verify.mjs exits 0 on 258 checks.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0004-package-contract-v1-and-rulings.md'],
  },
  {
    id: 'pkg-contract-draft2',
    title: 'Deal Terms release-package contract, draft 2',
    plainEnglish: 'Second version, applying three agreed changes: who mints the deal ID, typed values on every field, and splitting the corpus list from the admission receipt.',
    group: 'package',
    scope: 'Applies A-0004\'s three accepted rulings: DS mints transaction_id (package carries both transaction_id and PM\'s deal_key), typed value_type/typed_value/unit/sort_value on every field, and the selection-record-plus-admission-receipt corpus split adopted verbatim. Refuses the fourth (a producer relevance score).',
    dependsOn: ['pkg-contract-draft1'],
    owner: 'ext',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Next A on the channel; not yet posted.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown('No range given; A-0004 says only "draft 2 is the next A".'),
    evidence: 'Planned: regenerated schema, example and verify run under docs/codex-program/handoffs/deal-terms/contract/, posted as the next outbox/A-NNNN.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0004-package-contract-v1-and-rulings.md "Next"'],
  },
  {
    id: 'pkg-one-deal',
    title: 'One-deal package (wiring only)',
    plainEnglish: 'Ship one deal in that format purely to wire up the consumer. Everything is marked review-only and none of it is shown to users.',
    group: 'package',
    scope: 'Cut from the first real ten-agreement V2 run, one of the ten sealed agreements. release_state REVIEW_ONLY_INTERNAL, public: false. Every claim carries review state, expected REVIEW_ONLY for every occurrence by design. For wiring the consumer, never for showing users.',
    dependsOn: ['repair-phase1-issue-only-run', 'pkg-contract-draft2'],
    owner: 'lead',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Waiting on the first real ten-agreement run and the finished package contract.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: a released package cut from the Phase 1 issue-only output.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0002-approach-corpus-and-packages.md "Packages"'],
    releaseState: 'REVIEW_ONLY_INTERNAL',
    userFacing: false,
    publicRequires: 'product-stage-9',
  },
  {
    id: 'pkg-five-deal-wiring',
    title: 'Five-deal package (wiring only)',
    plainEnglish: 'The same, with five deals, once the extracted values actually mean something. Enough to test cross-deal search and comparison.',
    group: 'package',
    scope: 'Same contract, five of the ten sealed agreements, after Phase 2 extraction and Ben\'s profile session, when claims carry NORMAL/APPROVED_LIMITED/REVIEW_ONLY states that mean something. release_state REVIEW_ONLY_INTERNAL still, until M7 seals. Needed for cross-deal search, comparison, typed missing states, update and rollback; does not pass the combined five-deal product gate.',
    dependsOn: ['repair-phase2-extraction', 'pkg-one-deal'],
    owner: 'lead',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Waiting on Phase 2 extraction/profiles and the one-deal package.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: a released five-deal package, wiring-only.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0002-approach-corpus-and-packages.md "Packages"', 'coord/deal-terms handoffs/deal-terms/inbox/Q-0001-consumer-contract-requirements.md "§4 Package order and use"'],
    releaseState: 'REVIEW_ONLY_INTERNAL',
    userFacing: false,
    publicRequires: 'product-stage-9',
  },
  {
    id: 'pkg-five-deal-reissue',
    title: 'Five-deal package, reissued after the producer legal gate',
    plainEnglish: 'Reissue those five deals once the legal gate passes, so they may be displayed internally.',
    group: 'package',
    scope: 'Same five deals, reissued once the M7 V2 receipt seals. Still release_state REVIEW_ONLY_INTERNAL (A-0002 is explicit that this does not change), but permits internal user display and is the Deal Terms input to the combined five-deal product gate.',
    dependsOn: ['work7-verify-signoff', 'pkg-five-deal-wiring'],
    owner: 'lead',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Waiting on the sealed M7 V2 receipt.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: reissued five-deal package with internal-display-eligible states.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0002-approach-corpus-and-packages.md "Packages"'],
    releaseState: 'REVIEW_ONLY_INTERNAL',
    userFacing: 'internal',
    publicRequires: 'product-stage-9',
  },
  {
    id: 'pkg-corpus-extension-fifty',
    title: 'Shared 50-deal proof corpus: extend the 40 with ten more',
    plainEnglish: 'Ben names ten further deals on top of the 40, making the shared 50. He also decides how their facts get extracted.',
    group: 'package',
    scope: 'The 40-agreement certification corpus plus ten deals that Ben, not either agent, names. Admission is deterministic (M2, M3) plus typed extraction; typed facts for the ten new deals need either a model-assisted run (locked until M7 passes, and would need its own authorisation) or parser-only extraction with a large review-only residue -- Ben decides which.',
    dependsOn: ['product-stage-6'],
    owner: 'ben',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Waiting on the 40-agreement certification corpus, and on Ben naming the ten extension deals and the extraction method.',
    waitsOnBen: true,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: SHARED_50_DEAL_SELECTION/V1 selection record plus a separate admission receipt per deal.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0002-approach-corpus-and-packages.md "Corpus"', 'coord/deal-terms handoffs/deal-terms/inbox/Q-0001-consumer-contract-requirements.md "§3"'],
  },
  {
    id: 'pkg-fifty-deal-proof',
    title: 'Shared 50-deal proof package',
    plainEnglish: 'The full shared 50-deal package. It only becomes public under Ben\'s one-use production authority at Stage 9.',
    group: 'package',
    scope: 'Same contract, the full shared corpus. release_state becomes LEGAL_GATE_PASSED_INTERNAL only once the M7 V2 receipt is sealed AND the corpus admission receipt exists; PUBLIC only under Ben\'s one-use Product Stage 9 production authority.',
    dependsOn: ['pkg-corpus-extension-fifty', 'work7-verify-signoff'],
    owner: 'lead',
    externalChannel: 'deal-terms',
    status: 'not_started',
    blockedReason: 'Waiting on the corpus extension and the sealed M7 V2 receipt.',
    waitsOnBen: false,
    benQuestions: [],
    authorityRecord: null,
    estimate: estimateUnknown(AFTER_FIRST_REAL_RUN_UNKNOWN),
    evidence: 'Planned: the shared 50-deal proof package, internal proof only until Product Stage 9.',
    sources: ['coord/deal-terms handoffs/deal-terms/outbox/A-0002-approach-corpus-and-packages.md "Packages"'],
    releaseState: 'REVIEW_ONLY_INTERNAL',
    userFacing: false,
    publicRequires: 'product-stage-9',
  },
].map((t) => Object.freeze({ ...t, dependsOn: Object.freeze([...t.dependsOn]), benQuestions: Object.freeze([...t.benQuestions]), sources: Object.freeze([...t.sources]) })));

// Package tasks carry release-state metadata directly (releaseState,
// userFacing, publicRequires); this is that subset, not a second hand-
// authored dataset that could drift from TASKS.
const MILESTONES = Object.freeze(TASKS.filter((t) => t.group === 'package' && 'releaseState' in t));

// Internal proof, certification and production gates. `appliesTo` names
// the task ids a gate governs; every id must resolve against TASKS.
const GATES = Object.freeze([
  {
    id: 'gate-false-complete-guard',
    name: 'False-complete guard (real-agreement receipt guard)',
    kind: 'proof',
    description: 'A work receipt passes only if it binds one AGREEMENT_ANALYSIS/V2 per sealed Work 3 set member by record ID, validates against the Work 7 verifier, its governed_input_occurrence_ids equals the agreement\'s M4 claim set with every closure/context span hash-verified, binds a per-occurrence attempt record the external agent recomputes independently, binds the per-family reason-code count report, and the finaliser\'s tests are behavioural against a temporary tree with one analysis missing, malformed or changed. A synthetic text cannot satisfy this.',
    appliesTo: ['repair-phase1-issue-only-run', 'repair-phase2-extraction', 'repair-phase3-candidate-registration', 'work5-packet-session3', 'work6-rebind-rerun', 'work7-verify-signoff'],
    sources: ['docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §4 "The false-complete guard"'],
  },
  { id: 'gate-ci-baseline', name: 'gate:baseline', kind: 'ci', description: 'Named CI gate, not part of npm test. Runs in the evidence-gates CI job once per exact input digest; skipped on an exact checkpoint hit.', appliesTo: [], sources: ['CLAUDE.md "Three checks are named CI gates"'] },
  { id: 'gate-ci-near-miss', name: 'gate:near-miss', kind: 'ci', description: 'Re-derives a committed evidence report from every admitted corpus run; ~20 minutes; skipped on exact checkpoint hit.', appliesTo: [], sources: ['CLAUDE.md "Three checks are named CI gates"'] },
  { id: 'gate-ci-replay-baseline', name: 'gate:replay-baseline', kind: 'ci', description: 'Re-derives a committed evidence report from every admitted corpus run; ~20 minutes; skipped on exact checkpoint hit.', appliesTo: [], sources: ['CLAUDE.md "Three checks are named CI gates"'] },
  { id: 'gate-m7-legal', name: 'M7 legal-review gate (V2)', kind: 'legal', description: 'Ben\'s session 4 sign-off after a fresh-session adversarial review that wrote neither the candidate nor the plan. On PASS the M7 V2 repair receipt seals.', appliesTo: ['work7-verify-signoff'], sources: ['docs/core/PLAN.md §12 "M7" acceptance', 'docs/codex-program/notes/M7-V2-REPLAN-TO-PUBLICATION-2026-09-03.md §5 "Phase 3"'] },
  { id: 'gate-m9-cert', name: 'M9 certification', kind: 'certification', description: 'Every M0-M7 gate passes on the exact candidate; unexpected differences empty; full rollback restores prior digests; at least ten agreements certified.', appliesTo: ['m9-certification'], sources: ['docs/core/PLAN.md §14 "M9" acceptance'] },
  { id: 'gate-m10-activation', name: 'M10 activation', kind: 'certification', description: 'Exact M9 parity, zero family open-world increase, zero product writes, publication NONE, external serving disabled, proven restoration of the prior selector.', appliesTo: ['m10-activation'], sources: ['docs/core/PLAN.md §15 "M10" acceptance'] },
  { id: 'gate-product-stage-6-corpus', name: '40-agreement certification corpus', kind: 'certification', description: 'The exact manifest, 25 families, governed corpus open-world ledger, certified corpus candidate, corpus certificate and final receipt certify the complete product corpus.', appliesTo: ['product-stage-6'], sources: ['docs/core/PLAN.md §16 Stage 6'] },
  { id: 'gate-product-stage-9-cutover', name: 'Production cutover (one-use authority)', kind: 'production', description: 'Real product writes, serves, renders and rolls back under Ben\'s explicit, non-repeatable, one-use production authority. Mission-ready family set excludes Capitalisation.', appliesTo: ['product-stage-9'], sources: ['docs/core/PLAN.md §16 Stage 9'] },
]);

// Later Precedent Machine features and document-analysis branches: from
// PLAN.md's later stages (Stage 9F is already a task above; these are the
// items PLAN.md does not schedule at all) and GRAVEYARD.md's built-but-
// parked or needs-a-fresh-look entries. None of these have a dependsOn
// edge into TASKS -- they are not scheduled, only registered.
const LATER_FEATURES = Object.freeze([
  {
    id: 'later-amendment-full-diff',
    title: 'Amendment full diff in the review tab',
    kind: 'plan-later-stage',
    description: 'Detecting an amendment and showing a visible warning ships before launch; working out exactly what changed and showing it in the review tab is genuine post-launch work, deferred alongside export.',
    sources: ['docs/core/OPERATING-RULES.md "Displaying the finished analysis moves earlier..." (2026-08-05)'],
  },
  {
    id: 'later-export',
    title: 'Export',
    kind: 'plan-later-stage',
    description: 'Deferred post-launch work, alongside the amendment full diff.',
    sources: ['docs/core/OPERATING-RULES.md "Displaying the finished analysis moves earlier..." (2026-08-05)'],
  },
  {
    id: 'later-successor-process-domain',
    title: 'contracts/canonical-v2/successor/ -- the "process" domain (document-analysis branch)',
    kind: 'graveyard-revive-candidate',
    description: '180 files covering a next-generation process domain: agreements, events, narration, passages, relationships, and query compilers. ~35 lib/ files import it, ~90 tests exercise it. Two known user-facing entry points, both route-guarded to preview-or-local and synthetic fixture data only. GRAVEYARD.md\'s own recommendation: needs a dedicated follow-up audit before any keep, delete or revive call is made -- this is a pointer to where that audit should start, not a finished assessment.',
    sources: ['docs/core/GRAVEYARD.md §15 "contracts/canonical-v2/successor/"'],
  },
  {
    id: 'later-termination-fee-v3-v4',
    title: 'TERMINATION_FEE_TRIGGER_PATH_SCHEMA_V3/V4 -- built, validated, not registered to serve',
    kind: 'graveyard-revive-candidate',
    description: 'The payment-timing split (payment_trigger_event + payment_delay in place of V2\'s single payment_timing) is built, tested, and one committed step past its own production wiring. Blocked on a producer that actually emits a V3/V4-shaped effect for a real deal -- not a bug, a deliberate sequencing choice (producer before registration).',
    sources: ['docs/core/GRAVEYARD.md §16 "TERMINATION_FEE_TRIGGER_PATH_SCHEMA_V3, FIXTURE_CONTRACT_INPUT_V39"'],
  },
  {
    id: 'later-metric-scoped-serving-chain',
    title: 'Metric-scoped serving-admission chain (F16-F26) -- higher-rigour alternative',
    kind: 'graveyard-revive-candidate',
    description: 'Eleven modules implementing per-fact certification against reviewed evidence, built for NO_SHOP, real and passing but not extended to other families on cost grounds (DECISIONS.md #13). Kept on purpose: the right answer again if a specific family later needs certification-grade proof rather than corpus-equivalence proof.',
    sources: ['docs/core/GRAVEYARD.md §1 "The metric-scoped serving-admission chain (F16 to F26)"'],
  },
  {
    id: 'later-metsera-exclusivity-pilot',
    title: 'Metsera exclusivity pilot',
    kind: 'graveyard-revive-candidate',
    description: 'Fourteen live modules validating the process domain\'s design for one deal, kept as a historical proof-of-concept. Worth asking whether the frozen fixture still needs its own demo route, or whether a future pilot pass should reuse scripts/canonical-v2-live-extraction-run.mjs instead.',
    sources: ['docs/core/GRAVEYARD.md §12 "The Metsera exclusivity pilot"'],
  },
]);

module.exports = {
  BASE_COMMIT,
  AS_OF,
  CONTROLS,
  OPEN_BEN_RULINGS,
  TASKS,
  MILESTONES,
  GATES,
  LATER_FEATURES,
};
