const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync(
  'scripts/canonical-v2-staging-writer-structure-identity.mjs',
  'utf8',
);

test('structural identity acceptance is staging-only, bounded and rollback-bound', () => {
  assert.match(source, /createCanonicalV2StagingRuntime/);
  assert.match(source, /runtime\.guardProject\(\)/);
  assert.match(source, /buildQxoReviewedCapitalisationSlice/);
  assert.match(source, /buildValidatedDefinitionGraph/);
  assert.match(source, /De Minimis Inaccuracies/);
  assert.match(source, /buildProvisionComponent/);
  assert.match(source, /buildCanonicalWriteInputDigest/);
  assert.match(source, /WHEN SQLSTATE '23514'/);
  assert.match(source, /observed_sqlstate IS DISTINCT FROM '23514'/);
  assert.match(source, /first_result->>'replayed' IS DISTINCT FROM 'false'/);
  assert.match(source, /replay_result->>'replayed' IS DISTINCT FROM 'true'/);
  assert.match(source, /provision_mismatch_count/);
  assert.match(source, /component_mismatch_count/);
  assert.match(source, /forged excerpt identity/);
  assert.match(source, /excerpt on the wrong source occurrence/);
  assert.match(source, /unbound excerpt field/);
  assert.match(source, /re-signed excerpt bytes not present in source/);
  assert.match(source, /excerpt splitting a UTF-8 code point/);
  assert.match(source, /zero-length continuation-offset excerpt/);
  assert.match(source, /forged provision identity/);
  assert.match(source, /forged provision anchor/);
  assert.match(source, /re-signed wrong source occurrence/);
  assert.match(source, /whitespace-only provision concept/);
  assert.match(source, /provision splitting a UTF-8 code point/);
  assert.match(source, /forged component identity/);
  assert.match(source, /forged component anchor/);
  assert.match(source, /re-signed component outside parent/);
  assert.match(source, /re-signed component on unadmitted text/);
  assert.match(source, /whitespace-only component key/);
  assert.match(source, /component splitting a UTF-8 code point/);
  assert.match(source, /forged validated semantic graph identity/);
  assert.match(source, /valid empty semantic graph/);
  assert.match(source, /valid semantic graph use ending at source EOF/);
  assert.match(source, /re-signed forged definition cue identity/);
  assert.match(source, /re-signed forged definition use identity/);
  assert.match(source, /re-signed forged embedded semantic span identity/);
  assert.match(source, /re-signed definition term not present in source/);
  assert.match(source, /re-signed definition uses outside canonical order/);
  assert.match(source, /re-signed definition use linked to an unknown cue/);
  assert.match(source, /fully re-signed graph on an unadmitted document/);
  assert.match(source, /re-signed nested definition with invalid geometry/);
  assert.match(source, /semantic graph exceeding the governed child bound/);
  assert.match(source, /semantic graph with a scalar body-span collection/);
  assert.match(source, /semantic graph with a scalar cue-id collection/);
  assert.match(source, /scalar validated semantic graph node/);
  assert.match(source, /semantic graph with a scalar definition cue node/);
  assert.match(source, /semantic graph with a scalar definition use node/);
  assert.match(source, /semantic graph with a scalar embedded span node/);
  assert.match(source, /semantic graph span splitting a UTF-8 code point/);
  assert.match(source, /semantic graph request exceeding the aggregate child bound/);
  assert.match(source, /semantic graph request exceeding the aggregate body-span bound/);
  assert.match(source, /semantic graph request exceeding the aggregate top-level identifier bound/);
  assert.match(source, /semantic graph request exceeding the aggregate body identifier bound/);
  assert.match(source, /UNSAFE_PERSISTED_GRAPH_ORDINAL/);
  assert.match(source, /FRACTIONAL_PERSISTED_BODY_ID/);
  assert.match(source, /FRACTIONAL_PERSISTED_GRAPH_ID/);
  assert.match(source, /NON_ASCII_PERSISTED_GRAPH_ID/);
  assert.match(source, /persisted parent with zero-length continuation-offset component/);
  assert.match(source, /CANONICAL_V2_MALFORMED_PERSISTED_EXCERPT_BYTES/);
  assert.match(source, /malformed persisted \$\{target\.label\} was accepted/);
  assert.match(source, /table: 'provision_instances'/);
  assert.match(source, /table: 'excerpts'/);
  assert.match(source, /table: 'validated_semantic_graphs'/);
  assert.match(source, /INSERT INTO canonical_v2_staging\.\$\{target\.table\}/);
  assert.doesNotMatch(source, /commit:\s*true/);
  assert.doesNotMatch(source, /\bCOMMIT;/);
  assert.doesNotMatch(source, /tzulhdasmioeechxapdy/);
});
