'use strict';
const assert = require('node:assert/strict');
const test = require('node:test');
const { sha256Hex } = require('../lib/canonical-v2/canonical-bytes');
const { NOT_ISSUED, buildAllocationPersistenceReceiptProposal, validateAllocationPersistenceReceiptProposal, buildReviewedProductionDealBridgeProposal, validateReviewedProductionDealBridgeProposal, validateIssuedAllocationPersistenceReceipt, validateIssuedReviewedProductionDealBridge } = require('../lib/canonical-v2/deal-identity-allocation-readiness');
const { requireClosedPersistenceControllerInput, issueAllocationPersistenceReceipt, issueReviewedProductionDealBridge } = require('../lib/canonical-v2/deal-identity-persistence-controller-interface');
const id = (value) => sha256Hex(`identity:${value}`);
function receipt(index = 1) { return buildAllocationPersistenceReceiptProposal({ approval_or_frozen_issuer_authority_id: id(`authority-${index}`), expected_nonce_registry_version: index, expected_slot_version: index, governed_deal_key: id(`key-${index}`), manifest_id: id(`manifest-${index}`), nonce_registry_predecessor_id: id(`nonce-${index}`), seed_slot_predecessor_id: id(`slot-${index}`), serialisable_transaction_isolation_evidence_id: id(`isolation-${index}`), zero_conflicting_allocation_evidence_id: id(`zero-${index}`) }); }
test('allocation persistence receipt binds CAS predecessors but remains not issued', () => { const value = receipt(); assert.equal(value.status, NOT_ISSUED); assert.equal(value.persistence_authority, 'NONE'); assert.deepEqual(validateAllocationPersistenceReceiptProposal(value), value); for (const changed of [{ ...value, expected_slot_version: 2 }, { ...value, allocation_persistence_receipt_id: id('forged') }]) assert.throws(() => validateAllocationPersistenceReceiptProposal(changed)); });
test('bridge retains 40 unique deals, receipts and keys plus TopBuild second occurrence but remains not issued', () => { const receipts = Array.from({ length: 40 }, (_, i) => receipt(i + 1)); const bridge = buildReviewedProductionDealBridgeProposal({ initial_import_packet_id: id('packet'), source_root_id: id('root'), reviewed_mapping_approval_id: id('review'), mappings: receipts.map((item, i) => ({ production_deal_id: `deal-${i + 1}`, governed_deal_key: item.governed_deal_key, allocation_persistence_receipt_id: item.allocation_persistence_receipt_id })), occurrence_ids: [...Array.from({ length: 40 }, (_, i) => `deal-${i + 1}/PRIMARY`), 'TOPBUILD/SECOND_SEC_AGREEMENT_OCCURRENCE'] }); assert.equal(bridge.status, NOT_ISSUED); assert.deepEqual(validateReviewedProductionDealBridgeProposal(bridge), bridge); const forged = structuredClone(bridge); forged.mappings[1].governed_deal_key = forged.mappings[0].governed_deal_key; assert.throws(() => validateReviewedProductionDealBridgeProposal(forged)); const missingTopBuild = structuredClone(bridge); missingTopBuild.occurrence_ids[0] = 'TOPBUILD/PRIMARY'; assert.throws(() => validateReviewedProductionDealBridgeProposal(missingTopBuild)); });
test('proposal receipts and bridges cannot stand in for distinct issued evidence', () => { const proposed = receipt(); assert.throws(() => validateIssuedAllocationPersistenceReceipt(proposed)); assert.throws(() => validateIssuedReviewedProductionDealBridge({ schema_version: 'REVIEWED_PRODUCTION_DEAL_IDENTITY_BRIDGE_ISSUED/V1', status: 'ISSUED', bridge_root_id: id('root'), packet_id: id('packet'), production_deal_id: 'deal', issued_bridge_id: id('forged') })); });
test('closed controller interface validates the proposal pair and refuses every issuance path', () => { const allocation = receipt(); const bridge = buildReviewedProductionDealBridgeProposal({ initial_import_packet_id: id('packet'), source_root_id: id('root'), reviewed_mapping_approval_id: id('review'), mappings: Array.from({ length: 40 }, (_, i) => ({ production_deal_id: `deal-${i}`, governed_deal_key: i === 0 ? allocation.governed_deal_key : id(`key-x-${i}`), allocation_persistence_receipt_id: i === 0 ? allocation.allocation_persistence_receipt_id : id(`receipt-x-${i}`) })), occurrence_ids: [...Array.from({ length: 40 }, (_, i) => `deal-${i}/PRIMARY`), 'TOPBUILD/SECOND_SEC_AGREEMENT_OCCURRENCE'] }); assert.doesNotThrow(() => requireClosedPersistenceControllerInput({ allocation_receipt_proposal: allocation, reviewed_bridge_proposal: bridge })); assert.throws(() => issueAllocationPersistenceReceipt(), { code: 'IDENTITY_PERSISTENCE_CONTROLLER_NOT_IMPLEMENTED' }); assert.throws(() => issueReviewedProductionDealBridge(), { code: 'IDENTITY_BRIDGE_ISSUER_NOT_IMPLEMENTED' }); });
