'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { BACKUP_SCHEMA, CORE_TABLES, dumpDealBackup, restoreDealFromBackup, restorePlan } = require('../scripts/reprocess/v1-apply-backup');
const dealId = '7dc3a05f-b170-4d59-a255-b7103cca16e1';
function fakeSb() { return { from(table) { return { select() { return this; }, eq() { return Promise.resolve({ data: [{ id: table === 'deals' ? dealId : `${table}-1`, deal_id: dealId }], error: null }); } }; } }; }
test('backup captures core deal rows but labels the graph incomplete, rejects overwrite, and identifies exact orphans', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'v1-backup-')); const file = path.join(dir, 'backup.json'); const backup = await dumpDealBackup(fakeSb(), dealId, file); assert.equal(backup.schema, BACKUP_SCHEMA); assert.deepEqual(CORE_TABLES, ['deals', 'parser_regions', 'provisions', 'provision_cards', 'claims']); assert.equal(backup.graph.complete, false); await assert.rejects(() => dumpDealBackup(fakeSb(), dealId, file)); assert.deepEqual(restorePlan([{ id: 'a' }], [{ id: 'b' }]), { upsert: [{ id: 'a' }], delete_orphan_ids: ['b'] }); fs.rmSync(dir, { recursive: true }); });
test('restore cannot apply an incomplete graph backup', async () => { const backup = { schema: BACKUP_SCHEMA, dumpedAt: '2026-08-04T00:00:00.000Z', dealIds: [dealId], deals: [{ id: dealId }], parser_regions: [], provisions: [], provision_cards: [], claims: [], graph: { complete: false } }; await assert.rejects(() => restoreDealFromBackup(fakeSb(), backup, dealId, { apply: true, authority: { args: { apply: true, dealId, backup: 'x', confirmProduction: dealId }, env: { SUPABASE_SERVICE_ROLE_KEY: 'x', SUPABASE_URL: 'https://tzulhdasmioeechxapdy.supabase.co' }, backupFileContents: backup, authorityEvidence: { ruling_id: 'db-apply', choice_id: 'fixture-go', source_path: 'lib/programme-decision-console.js' } } }), { code: 'V1_RESTORE_INCOMPLETE_GRAPH' }); });
