// Generated by scripts/generate-registry.js. Hand-audit before editing.

const TAGS = {
  "EXCEPTION_CODES:WHOLLY_OWNED_SUB": {
    "code": "WHOLLY_OWNED_SUB",
    "family": "EXCEPTION_CODES",
    "label": "Transactions among wholly-owned subsidiaries",
    "description": "Transactions among wholly-owned subsidiaries taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:EQUITY_AWARD_MECHANICS": {
    "code": "EQUITY_AWARD_MECHANICS",
    "family": "EXCEPTION_CODES",
    "label": "Existing equity award exercises, vesting, or settlement",
    "description": "Existing equity award exercises, vesting, or settlement taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:EXISTING_FACILITIES": {
    "code": "EXISTING_FACILITIES",
    "family": "EXCEPTION_CODES",
    "label": "Existing credit facilities or indebtedness",
    "description": "Existing credit facilities or indebtedness taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:ORDINARY_COURSE": {
    "code": "ORDINARY_COURSE",
    "family": "EXCEPTION_CODES",
    "label": "Ordinary course of business",
    "description": "Ordinary course of business taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:DISCLOSURE_SCHEDULE": {
    "code": "DISCLOSURE_SCHEDULE",
    "family": "EXCEPTION_CODES",
    "label": "As disclosed",
    "description": "As disclosed taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:COMPANY_DISCLOSURE_LETTER": {
    "code": "COMPANY_DISCLOSURE_LETTER",
    "family": "EXCEPTION_CODES",
    "label": "As disclosed",
    "description": "As disclosed taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:REQUIRED_BY_LAW": {
    "code": "REQUIRED_BY_LAW",
    "family": "EXCEPTION_CODES",
    "label": "As required by law",
    "description": "As required by law taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:REQUIRED_BY_AGREEMENT": {
    "code": "REQUIRED_BY_AGREEMENT",
    "family": "EXCEPTION_CODES",
    "label": "As contemplated by this Agreement",
    "description": "As contemplated by this Agreement taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:WRITTEN_CONSENT": {
    "code": "WRITTEN_CONSENT",
    "family": "EXCEPTION_CODES",
    "label": "With Parent’s consent",
    "description": "With Parent’s consent taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:PRIOR_WRITTEN_CONSENT": {
    "code": "PRIOR_WRITTEN_CONSENT",
    "family": "EXCEPTION_CODES",
    "label": "With Parent’s consent",
    "description": "With Parent’s consent taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:COVID_MEASURES": {
    "code": "COVID_MEASURES",
    "family": "EXCEPTION_CODES",
    "label": "COVID-19 / pandemic response measures",
    "description": "COVID-19 / pandemic response measures taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:EXISTING_CONTRACTS": {
    "code": "EXISTING_CONTRACTS",
    "family": "EXCEPTION_CODES",
    "label": "Pursuant to existing contracts as of signing",
    "description": "Pursuant to existing contracts as of signing taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:TAX_WITHHOLDING": {
    "code": "TAX_WITHHOLDING",
    "family": "EXCEPTION_CODES",
    "label": "Tax withholding or similar mandated actions",
    "description": "Tax withholding or similar mandated actions taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:INTERCOMPANY": {
    "code": "INTERCOMPANY",
    "family": "EXCEPTION_CODES",
    "label": "Intercompany transactions",
    "description": "Intercompany transactions taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:TRADE_PAYABLES": {
    "code": "TRADE_PAYABLES",
    "family": "EXCEPTION_CODES",
    "label": "Trade payables in ordinary course",
    "description": "Trade payables in ordinary course taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:EMERGENCY_LIFE_SAFETY": {
    "code": "EMERGENCY_LIFE_SAFETY",
    "family": "EXCEPTION_CODES",
    "label": "Emergency, life, or safety reasons",
    "description": "Emergency, life, or safety reasons taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:MONETARY_THRESHOLD": {
    "code": "MONETARY_THRESHOLD",
    "family": "EXCEPTION_CODES",
    "label": "Below monetary threshold",
    "description": "Below monetary threshold taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:BUDGET_EXCEPTION": {
    "code": "BUDGET_EXCEPTION",
    "family": "EXCEPTION_CODES",
    "label": "Within budget / capex plan",
    "description": "Within budget / capex plan taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:FIDUCIARY_OUT": {
    "code": "FIDUCIARY_OUT",
    "family": "EXCEPTION_CODES",
    "label": "Fiduciary out for Superior Proposal",
    "description": "Fiduciary out for Superior Proposal taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:UNSOLICITED_PROPOSAL": {
    "code": "UNSOLICITED_PROPOSAL",
    "family": "EXCEPTION_CODES",
    "label": "Response to unsolicited acquisition proposal",
    "description": "Response to unsolicited acquisition proposal taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:ACCEPTABLE_CONFI_AGREEMENT": {
    "code": "ACCEPTABLE_CONFI_AGREEMENT",
    "family": "EXCEPTION_CODES",
    "label": "Information sharing under acceptable confidentiality agreement",
    "description": "Information sharing under acceptable confidentiality agreement taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:BURDENSOME_CONDITION_CAP": {
    "code": "BURDENSOME_CONDITION_CAP",
    "family": "EXCEPTION_CODES",
    "label": "Subject to burdensome condition cap",
    "description": "Subject to burdensome condition cap taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EXCEPTION_CODES:OTHER": {
    "code": "OTHER",
    "family": "EXCEPTION_CODES",
    "label": "Other specific exception (see text)",
    "description": "Other specific exception (see text) taxonomy tag.",
    "appearsOn": [
      "absenceOfChangesExceptions",
      "negativePreambleExceptions",
      "undisclosedLiabilitiesExceptions"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "ANTITRUST_APPROVAL_CODES:HSR": {
    "code": "HSR",
    "family": "ANTITRUST_APPROVAL_CODES",
    "label": "HSR Act waiting period expired or terminated",
    "description": "HSR Act waiting period expired or terminated taxonomy tag.",
    "appearsOn": [
      "antitrustApprovals"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "ANTITRUST_APPROVAL_CODES:SCHEDULED_APPROVALS": {
    "code": "SCHEDULED_APPROVALS",
    "family": "ANTITRUST_APPROVAL_CODES",
    "label": "Other scheduled regulatory approvals obtained",
    "description": "Other scheduled regulatory approvals obtained taxonomy tag.",
    "appearsOn": [
      "antitrustApprovals"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:STOCK_OPTIONS": {
    "code": "STOCK_OPTIONS",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Stock Options",
    "description": "Stock Options taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:RSUs": {
    "code": "RSUs",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Restricted Stock Units (RSUs)",
    "description": "Restricted Stock Units (RSUs) taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:PSUs": {
    "code": "PSUs",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Performance Stock Units (PSUs)",
    "description": "Performance Stock Units (PSUs) taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:RESTRICTED_STOCK": {
    "code": "RESTRICTED_STOCK",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Restricted Stock Awards",
    "description": "Restricted Stock Awards taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:WARRANTS": {
    "code": "WARRANTS",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Warrants",
    "description": "Warrants taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:ESPP": {
    "code": "ESPP",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Employee Stock Purchase Plan rights",
    "description": "Employee Stock Purchase Plan rights taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:CONVERTIBLE_NOTES": {
    "code": "CONVERTIBLE_NOTES",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Convertible Notes",
    "description": "Convertible Notes taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:SARS": {
    "code": "SARS",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Stock Appreciation Rights",
    "description": "Stock Appreciation Rights taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:PHANTOM_STOCK": {
    "code": "PHANTOM_STOCK",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Phantom Stock",
    "description": "Phantom Stock taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_INSTRUMENTS:DEFERRED_COMPENSATION": {
    "code": "DEFERRED_COMPENSATION",
    "family": "EQUITY_INSTRUMENTS",
    "label": "Deferred Compensation Awards",
    "description": "Deferred Compensation Awards taxonomy tag.",
    "appearsOn": [
      "outstandingInstruments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:CASHED_OUT_AT_CONSIDERATION": {
    "code": "CASHED_OUT_AT_CONSIDERATION",
    "family": "EQUITY_TREATMENT",
    "label": "Cashed out at Merger Consideration",
    "description": "Cashed out at Merger Consideration taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:CASHED_OUT_SPREAD": {
    "code": "CASHED_OUT_SPREAD",
    "family": "EQUITY_TREATMENT",
    "label": "Cashed Out at Spread",
    "description": "Cashed Out at Spread taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:ACCELERATED_VESTING": {
    "code": "ACCELERATED_VESTING",
    "family": "EQUITY_TREATMENT",
    "label": "Vesting accelerated and cashed out",
    "description": "Vesting accelerated and cashed out taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:PARTIAL_ACCELERATION": {
    "code": "PARTIAL_ACCELERATION",
    "family": "EQUITY_TREATMENT",
    "label": "Partial vesting acceleration",
    "description": "Partial vesting acceleration taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:ASSUMED_BY_BUYER": {
    "code": "ASSUMED_BY_BUYER",
    "family": "EQUITY_TREATMENT",
    "label": "Assumed and converted to buyer equity",
    "description": "Assumed and converted to buyer equity taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:CANCELLED_NO_CONSIDERATION": {
    "code": "CANCELLED_NO_CONSIDERATION",
    "family": "EQUITY_TREATMENT",
    "label": "Cancelled without consideration",
    "description": "Cancelled without consideration taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:CONTINUED_VESTING": {
    "code": "CONTINUED_VESTING",
    "family": "EQUITY_TREATMENT",
    "label": "Continues vesting on original schedule (no change)",
    "description": "Continues vesting on original schedule (no change) taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:REPLACEMENT_AWARDS": {
    "code": "REPLACEMENT_AWARDS",
    "family": "EQUITY_TREATMENT",
    "label": "Cancelled and replaced with retention awards",
    "description": "Cancelled and replaced with retention awards taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:DOUBLE_TRIGGER": {
    "code": "DOUBLE_TRIGGER",
    "family": "EQUITY_TREATMENT",
    "label": "Double-trigger acceleration (closing + qualifying termination)",
    "description": "Double-trigger acceleration (closing + qualifying termination) taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "EQUITY_TREATMENT:PARACHUTE_LIMITED": {
    "code": "PARACHUTE_LIMITED",
    "family": "EQUITY_TREATMENT",
    "label": "Subject to 280G parachute payment limits",
    "description": "Subject to 280G parachute payment limits taxonomy tag.",
    "appearsOn": [
      "instrumentTreatments"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:FULLY_ACCELERATED": {
    "code": "FULLY_ACCELERATED",
    "family": "VESTING_STATUS",
    "label": "Fully accelerated at closing",
    "description": "Fully accelerated at closing taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:PARTIALLY_ACCELERATED": {
    "code": "PARTIALLY_ACCELERATED",
    "family": "VESTING_STATUS",
    "label": "Partially accelerated at closing",
    "description": "Partially accelerated at closing taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:DOUBLE_TRIGGER_ACCEL": {
    "code": "DOUBLE_TRIGGER_ACCEL",
    "family": "VESTING_STATUS",
    "label": "Acceleration on double trigger (closing + termination)",
    "description": "Acceleration on double trigger (closing + termination) taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:ACCEL_ELSE_DOUBLE_TRIGGER": {
    "code": "ACCEL_ELSE_DOUBLE_TRIGGER",
    "family": "VESTING_STATUS",
    "label": "Accelerates if it vests by its terms; otherwise rolls over subject to double-trigger vesting",
    "description": "Accelerates if it vests by its terms; otherwise rolls over subject to double-trigger vesting taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:NO_ACCELERATION": {
    "code": "NO_ACCELERATION",
    "family": "VESTING_STATUS",
    "label": "No acceleration; continues vesting",
    "description": "No acceleration; continues vesting taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:TIME_BASED_VESTING": {
    "code": "TIME_BASED_VESTING",
    "family": "VESTING_STATUS",
    "label": "Time-based vesting per original schedule",
    "description": "Time-based vesting per original schedule taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:PERFORMANCE_DEEMED_ACHIEVED": {
    "code": "PERFORMANCE_DEEMED_ACHIEVED",
    "family": "VESTING_STATUS",
    "label": "Performance conditions deemed achieved",
    "description": "Performance conditions deemed achieved taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "VESTING_STATUS:PERFORMANCE_PRORATED": {
    "code": "PERFORMANCE_PRORATED",
    "family": "VESTING_STATUS",
    "label": "Performance conditions prorated",
    "description": "Performance conditions prorated taxonomy tag.",
    "appearsOn": [
      "instrumentVesting"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:NO_LESS_FAVORABLE": {
    "code": "NO_LESS_FAVORABLE",
    "family": "COMP_STANDARDS",
    "label": "No less favorable than current",
    "description": "No less favorable than current taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:SUBSTANTIALLY_SIMILAR": {
    "code": "SUBSTANTIALLY_SIMILAR",
    "family": "COMP_STANDARDS",
    "label": "Substantially similar to current",
    "description": "Substantially similar to current taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:SUBSTANTIALLY_COMPARABLE": {
    "code": "SUBSTANTIALLY_COMPARABLE",
    "family": "COMP_STANDARDS",
    "label": "Substantially comparable to current",
    "description": "Substantially comparable to current taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:IN_THE_AGGREGATE": {
    "code": "IN_THE_AGGREGATE",
    "family": "COMP_STANDARDS",
    "label": "In the aggregate (rebalancing permitted)",
    "description": "In the aggregate (rebalancing permitted) taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:COMPARABLE_TO_BUYER_EMPLOYEES": {
    "code": "COMPARABLE_TO_BUYER_EMPLOYEES",
    "family": "COMP_STANDARDS",
    "label": "Comparable to similarly situated buyer employees",
    "description": "Comparable to similarly situated buyer employees taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:BUYER_DISCRETION": {
    "code": "BUYER_DISCRETION",
    "family": "COMP_STANDARDS",
    "label": "At buyer's discretion",
    "description": "At buyer's discretion taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "COMP_STANDARDS:TARGET_BASELINE": {
    "code": "TARGET_BASELINE",
    "family": "COMP_STANDARDS",
    "label": "At target's pre-closing levels",
    "description": "At target's pre-closing levels taxonomy tag.",
    "appearsOn": [
      "compensationItems"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:ECONOMY_GENERAL": {
    "code": "ECONOMY_GENERAL",
    "family": "MAE_CARVEOUT_CODES",
    "label": "General economic conditions",
    "description": "General economic conditions taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:INDUSTRY_GENERAL": {
    "code": "INDUSTRY_GENERAL",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Industry-wide conditions",
    "description": "Industry-wide conditions taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:FINANCIAL_MARKETS": {
    "code": "FINANCIAL_MARKETS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Financial / capital / credit market conditions",
    "description": "Financial / capital / credit market conditions taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:ACTS_OF_WAR_TERRORISM": {
    "code": "ACTS_OF_WAR_TERRORISM",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Acts of war, armed hostilities, or terrorism",
    "description": "Acts of war, armed hostilities, or terrorism taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:NATURAL_DISASTERS": {
    "code": "NATURAL_DISASTERS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Natural disasters or acts of God",
    "description": "Natural disasters or acts of God taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:PANDEMIC": {
    "code": "PANDEMIC",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Pandemic / epidemic / public health crisis",
    "description": "Pandemic / epidemic / public health crisis taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:ANNOUNCEMENT_OR_PENDENCY": {
    "code": "ANNOUNCEMENT_OR_PENDENCY",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Announcement or pendency of the transaction",
    "description": "Announcement or pendency of the transaction taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:COMPLIANCE_WITH_AGREEMENT": {
    "code": "COMPLIANCE_WITH_AGREEMENT",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Compliance with the terms of this Agreement",
    "description": "Compliance with the terms of this Agreement taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:ACTIONS_REQUESTED_BY_PARENT": {
    "code": "ACTIONS_REQUESTED_BY_PARENT",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Actions taken at the request or with consent of Parent",
    "description": "Actions taken at the request or with consent of Parent taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:CHANGE_IN_LAW": {
    "code": "CHANGE_IN_LAW",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Changes in applicable law or regulation",
    "description": "Changes in applicable law or regulation taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:CHANGE_IN_GAAP": {
    "code": "CHANGE_IN_GAAP",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Changes in GAAP or accounting principles",
    "description": "Changes in GAAP or accounting principles taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:STOCK_PRICE_CHANGES": {
    "code": "STOCK_PRICE_CHANGES",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Changes in the trading price or volume of stock",
    "description": "Changes in the trading price or volume of stock taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:FAILURE_TO_MEET_PROJECTIONS": {
    "code": "FAILURE_TO_MEET_PROJECTIONS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Failure to meet internal projections or forecasts",
    "description": "Failure to meet internal projections or forecasts taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:PRICING_MFN": {
    "code": "PRICING_MFN",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Most-favored-nation pricing actions",
    "description": "Most-favored-nation pricing actions taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:EXECUTIVE_ACTION": {
    "code": "EXECUTIVE_ACTION",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Executive orders / sanctions / tariffs",
    "description": "Executive orders / sanctions / tariffs taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:TARIFFS": {
    "code": "TARIFFS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Tariffs / trade barriers",
    "description": "Tariffs / trade barriers taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:GOVERNMENT_SHUTDOWNS": {
    "code": "GOVERNMENT_SHUTDOWNS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Government shutdowns / civil unrest",
    "description": "Government shutdowns / civil unrest taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:CLINICAL_RESULTS": {
    "code": "CLINICAL_RESULTS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Clinical trial results (life sciences)",
    "description": "Clinical trial results (life sciences) taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:FDA_DISCUSSIONS": {
    "code": "FDA_DISCUSSIONS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "FDA discussions or correspondence (life sciences)",
    "description": "FDA discussions or correspondence (life sciences) taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:FDA_APPROVALS_COMPETITOR_ENTRY": {
    "code": "FDA_APPROVALS_COMPETITOR_ENTRY",
    "family": "MAE_CARVEOUT_CODES",
    "label": "FDA approvals of competitor products / competitor entry",
    "description": "FDA approvals of competitor products / competitor entry taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:SUPPLY_CHAIN": {
    "code": "SUPPLY_CHAIN",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Supply chain disruptions",
    "description": "Supply chain disruptions taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:PRICING_REIMBURSEMENT": {
    "code": "PRICING_REIMBURSEMENT",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Pricing / reimbursement changes (healthcare)",
    "description": "Pricing / reimbursement changes (healthcare) taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:MEDICAL_ORGS_STATEMENTS": {
    "code": "MEDICAL_ORGS_STATEMENTS",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Statements by medical / scientific organizations",
    "description": "Statements by medical / scientific organizations taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:PATENTS_EXCLUSIVITY": {
    "code": "PATENTS_EXCLUSIVITY",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Patent expirations / loss of exclusivity",
    "description": "Patent expirations / loss of exclusivity taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:PARENT_ACTIONS_OR_INACTION": {
    "code": "PARENT_ACTIONS_OR_INACTION",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Acts or omissions of Parent / Buyer",
    "description": "Acts or omissions of Parent / Buyer taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:EMPLOYEE_DEPARTURES": {
    "code": "EMPLOYEE_DEPARTURES",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Loss of employees or executive departures",
    "description": "Loss of employees or executive departures taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MAE_CARVEOUT_CODES:OTHER": {
    "code": "OTHER",
    "family": "MAE_CARVEOUT_CODES",
    "label": "Other carve-out",
    "description": "Other carve-out taxonomy tag.",
    "appearsOn": [
      "carveouts",
      "disproportionateImpactCarveouts",
      "nonDisproportionateImpactCarveouts"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:ACQUISITIONS": {
    "code": "ACQUISITIONS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Acquisitions / business combinations",
    "description": "Acquisitions / business combinations taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:ASSET_SALES_LICENSES": {
    "code": "ASSET_SALES_LICENSES",
    "family": "IOC_CATEGORY_CODES",
    "label": "Asset sales / divestitures / licenses",
    "description": "Asset sales / divestitures / licenses taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:MERGE_DISSOLVE_RECAP": {
    "code": "MERGE_DISSOLVE_RECAP",
    "family": "IOC_CATEGORY_CODES",
    "label": "Merger / consolidation / liquidation / recapitalization",
    "description": "Merger / consolidation / liquidation / recapitalization taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:INDEBTEDNESS": {
    "code": "INDEBTEDNESS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Indebtedness / financing",
    "description": "Indebtedness / financing taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:THIRD_PARTY_OBLIGATIONS": {
    "code": "THIRD_PARTY_OBLIGATIONS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Guarantees / third-party obligations",
    "description": "Guarantees / third-party obligations taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:LOANS_ADVANCES_CONTRIBUTIONS": {
    "code": "LOANS_ADVANCES_CONTRIBUTIONS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Loans / advances / capital contributions",
    "description": "Loans / advances / capital contributions taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:CAPEX": {
    "code": "CAPEX",
    "family": "IOC_CATEGORY_CODES",
    "label": "Capital expenditures",
    "description": "Capital expenditures taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:LITIGATION_SETTLEMENTS": {
    "code": "LITIGATION_SETTLEMENTS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Litigation settlements",
    "description": "Litigation settlements taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:NEW_CONTRACTS": {
    "code": "NEW_CONTRACTS",
    "family": "IOC_CATEGORY_CODES",
    "label": "New material contracts",
    "description": "New material contracts taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:CONTRACT_AMENDMENTS": {
    "code": "CONTRACT_AMENDMENTS",
    "family": "IOC_CATEGORY_CODES",
    "label": "Contract amendments / terminations",
    "description": "Contract amendments / terminations taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:EMPLOYEE_COMP": {
    "code": "EMPLOYEE_COMP",
    "family": "IOC_CATEGORY_CODES",
    "label": "Employee compensation / benefit increases",
    "description": "Employee compensation / benefit increases taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:REAL_ESTATE": {
    "code": "REAL_ESTATE",
    "family": "IOC_CATEGORY_CODES",
    "label": "Real estate / leases",
    "description": "Real estate / leases taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:IP_LICENSES": {
    "code": "IP_LICENSES",
    "family": "IOC_CATEGORY_CODES",
    "label": "Intellectual property licenses / assignments",
    "description": "Intellectual property licenses / assignments taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "IOC_CATEGORY_CODES:OTHER": {
    "code": "OTHER",
    "family": "IOC_CATEGORY_CODES",
    "label": "Other / unspecified",
    "description": "Other / unspecified taxonomy tag.",
    "appearsOn": [
      "dollarThresholdsByCategory"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:AGGREGATE_PAYMENTS": {
    "code": "AGGREGATE_PAYMENTS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Contracts above an aggregate-payments threshold",
    "description": "Contracts above an aggregate-payments threshold taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:INDEBTEDNESS": {
    "code": "INDEBTEDNESS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Indebtedness contracts",
    "description": "Indebtedness contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:JV_PARTNERSHIPS": {
    "code": "JV_PARTNERSHIPS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Joint ventures / partnerships",
    "description": "Joint ventures / partnerships taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:MA_AGREEMENTS": {
    "code": "MA_AGREEMENTS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "M&A / acquisition agreements",
    "description": "M&A / acquisition agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:IP_LICENSES_IN": {
    "code": "IP_LICENSES_IN",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Inbound IP licenses",
    "description": "Inbound IP licenses taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:IP_LICENSES_OUT": {
    "code": "IP_LICENSES_OUT",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Outbound IP licenses",
    "description": "Outbound IP licenses taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:SUPPLY": {
    "code": "SUPPLY",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Supplier agreements",
    "description": "Supplier agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:MANUFACTURE": {
    "code": "MANUFACTURE",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Manufacturing agreements",
    "description": "Manufacturing agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:DISTRIBUTION": {
    "code": "DISTRIBUTION",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Distribution / reseller agreements",
    "description": "Distribution / reseller agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:COLLABORATION": {
    "code": "COLLABORATION",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Collaboration / R&D agreements",
    "description": "Collaboration / R&D agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:SETTLEMENT": {
    "code": "SETTLEMENT",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Settlement / consent agreements",
    "description": "Settlement / consent agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:NONCOMPETE": {
    "code": "NONCOMPETE",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Non-competition / non-solicitation agreements",
    "description": "Non-competition / non-solicitation agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:REAL_ESTATE": {
    "code": "REAL_ESTATE",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Real estate leases",
    "description": "Real estate leases taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:EMPLOYMENT_KEY": {
    "code": "EMPLOYMENT_KEY",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Key employment / executive agreements",
    "description": "Key employment / executive agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:GOVERNMENT_CONTRACTS": {
    "code": "GOVERNMENT_CONTRACTS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Government contracts",
    "description": "Government contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:AFFILIATE_TRANSACTIONS": {
    "code": "AFFILIATE_TRANSACTIONS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Affiliate / related-party transactions",
    "description": "Affiliate / related-party transactions taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:EXCLUSIVITY_MFN": {
    "code": "EXCLUSIVITY_MFN",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Exclusivity / most-favored-nation / standstill",
    "description": "Exclusivity / most-favored-nation / standstill taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:CAPEX_COMMITMENTS": {
    "code": "CAPEX_COMMITMENTS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Capital expenditure commitments",
    "description": "Capital expenditure commitments taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:DATA_PRIVACY": {
    "code": "DATA_PRIVACY",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Data privacy / security agreements",
    "description": "Data privacy / security agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:VOTING_REGISTRATION_RIGHTS": {
    "code": "VOTING_REGISTRATION_RIGHTS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Voting / registration-rights / stockholder agreements",
    "description": "Voting / registration-rights / stockholder agreements taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:SEC_ITEM_601": {
    "code": "SEC_ITEM_601",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "SEC Item 601(b) contracts",
    "description": "SEC Item 601(b) contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:IP_DEVELOPMENT": {
    "code": "IP_DEVELOPMENT",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "IP development contracts",
    "description": "IP development contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:SINGLE_SOURCE": {
    "code": "SINGLE_SOURCE",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Single source procurement contracts",
    "description": "Single source procurement contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:CRO": {
    "code": "CRO",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Clinical research organization contracts",
    "description": "Clinical research organization contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:MA_ONGOING_OBLIGATIONS": {
    "code": "MA_ONGOING_OBLIGATIONS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "M&A agreements with ongoing obligations",
    "description": "M&A agreements with ongoing obligations taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:ROFR_ROFN": {
    "code": "ROFR_ROFN",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Agreements with ROFO/ROFN",
    "description": "Agreements with ROFO/ROFN taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:HEDGING": {
    "code": "HEDGING",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Hedging and derivative contracts",
    "description": "Hedging and derivative contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:EMPLOYEE_LOANS": {
    "code": "EMPLOYEE_LOANS",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Employee loans and advances",
    "description": "Employee loans and advances taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  },
  "MATERIAL_CONTRACT_BUCKET_CODES:OTHER": {
    "code": "OTHER",
    "family": "MATERIAL_CONTRACT_BUCKET_CODES",
    "label": "Other material contracts",
    "description": "Other material contracts taxonomy tag.",
    "appearsOn": [
      "materialContractsBuckets"
    ],
    "aliases": null,
    "benchmarkable": false
  }
};

for (const tag of Object.values(TAGS)) {
  if (tag.family === "EXCEPTION_CODES" && !tag.appearsOn.includes("permittedExceptions")) {
    tag.appearsOn.push("permittedExceptions");
  }
}

module.exports = { TAGS };
