/**
 * rubric.js — Single source of truth for the M&A provision rubric.
 *
 * Consumed by both the parser (AI classification) and the UI (labels,
 * feature extraction, comparison grids).  CommonJS for Next.js API-route
 * compatibility.
 *
 * Canonical reference: /RUBRIC.md
 */

// ---------------------------------------------------------------------------
// 1. PROVISION_TYPES — ordered array of every top-level provision category
// ---------------------------------------------------------------------------

const PROVISION_TYPES = [
  {
    key: 'STRUCT',
    label: 'Merger Structure & Mechanics',
    description: 'Merger mechanics, closing, effective time, charter/bylaw treatment, directors & officers',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'CONSID',
    label: 'Consideration & Securities Treatment',
    description: 'Share conversion, exchange mechanics, equity award treatment, appraisal rights',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'REP-T',
    label: 'Representations & Warranties (Target)',
    description: 'Representations and warranties made by the target / company',
    classificationMode: 'single',
    party: 'target',
  },
  {
    key: 'REP-B',
    label: 'Representations & Warranties (Buyer)',
    description: 'Representations and warranties made by the buyer / parent',
    classificationMode: 'single',
    party: 'buyer',
  },
  {
    key: 'IOC',
    label: 'Interim Operating Covenants',
    description: 'Sub-clause restrictions on target conduct between signing and closing',
    classificationMode: 'single',
    party: 'target',
  },
  {
    key: 'NOSOL',
    label: 'No-Solicitation / No-Shop',
    description: 'Solicitation prohibition, fiduciary out, matching rights, go-shop windows',
    classificationMode: 'multi',
    party: 'target',
  },
  {
    key: 'ANTI',
    label: 'Antitrust / Regulatory Efforts',
    description: 'HSR filings, efforts standard, divestiture caps, regulatory cooperation',
    classificationMode: 'multi',
    party: 'mutual',
  },
  {
    key: 'COND-M',
    label: 'Conditions to Closing (Mutual)',
    description: 'Conditions that must be satisfied for both parties to close',
    classificationMode: 'single',
    party: 'mutual',
  },
  {
    key: 'COND-B',
    label: 'Conditions to Closing (Buyer)',
    description: 'Conditions to the buyer\'s obligation to close',
    classificationMode: 'single',
    party: 'buyer',
  },
  {
    key: 'COND-S',
    label: 'Conditions to Closing (Seller/Target)',
    description: 'Conditions to the seller\'s / target\'s obligation to close',
    classificationMode: 'single',
    party: 'target',
  },
  {
    key: 'COND',
    label: 'Condition Modifiers',
    description: 'Frustration of conditions, tax opinion conditions',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'TERMR',
    label: 'Termination Rights',
    description: 'Mutual termination, outside date, breach termination, superior proposal termination',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'TERMF',
    label: 'Termination Fees & Expenses',
    description: 'Company termination fee, reverse termination fee, expense reimbursement, tail provisions',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'DEF',
    label: 'Definitions',
    description: 'Key negotiated defined terms (MAE, Superior Proposal, Knowledge, etc.)',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'COV',
    label: 'Other Covenants (Additional Agreements)',
    description: 'Access, proxy, stockholder meeting, publicity, indemnification, employee matters',
    classificationMode: 'single',
    party: null,
  },
  {
    key: 'MISC',
    label: 'Miscellaneous / Boilerplate',
    description: 'Governing law, notices, jury waiver, specific performance, amendment, boilerplate',
    classificationMode: 'single',
    party: null,
  },
];

// ---------------------------------------------------------------------------
// 2. CODES — flat object keyed by canonical code
// ---------------------------------------------------------------------------

const CODES = {
  // ── STRUCT ───────────────────────────────────────────────────────────────
  'STRUCT-MERGER': {
    type: 'STRUCT',
    label: 'The Merger',
    description: 'Core merger transaction provision',
    aliases: ['Merger', 'The Merger Transaction'],
    frequency: 'universal',
    industries: [],
  },
  'STRUCT-CLOSING': {
    type: 'STRUCT',
    label: 'Closing',
    description: 'Closing date, location, and mechanics',
    aliases: ['Closing Date', 'Closing of the Merger'],
    frequency: 'universal',
    industries: [],
  },
  'STRUCT-EFFTIME': {
    type: 'STRUCT',
    label: 'Effective Time',
    description: 'Certificate of merger filing and effective time',
    aliases: ['Effective Time of the Merger', 'Filing of Certificate of Merger'],
    frequency: 'universal',
    industries: [],
  },
  'STRUCT-EFFECTS': {
    type: 'STRUCT',
    label: 'Effects of the Merger',
    description: 'Legal consequences of the merger becoming effective',
    aliases: ['Effects of Merger', 'Effect of the Merger'],
    frequency: 'near-universal',
    industries: [],
  },
  'STRUCT-CHARTER': {
    type: 'STRUCT',
    label: 'Certificate of Incorporation / Bylaws',
    description: 'Post-merger charter and bylaw treatment of surviving entity',
    aliases: ['Charter Documents', 'Organizational Documents of the Surviving Corporation'],
    frequency: 'universal',
    industries: [],
  },
  'STRUCT-DIRECTORS': {
    type: 'STRUCT',
    label: 'Directors and Officers',
    description: 'Directors and officers of the surviving entity post-merger',
    aliases: ['Directors and Officers of the Surviving Corporation'],
    frequency: 'near-universal',
    industries: [],
  },
  'STRUCT-ACTIONS': {
    type: 'STRUCT',
    label: 'Subsequent Actions',
    description: 'Further corporate actions to effectuate the merger',
    aliases: ['Additional Actions', 'Further Actions'],
    frequency: 'common',
    industries: [],
  },

  // ── CONSID ──────────────────────────────────────────────────────────────
  'CONSID-CONVERT': {
    type: 'CONSID',
    label: 'Conversion of Shares / Effect on Capital Stock',
    description: 'Treatment of each share of target stock upon merger effectiveness',
    aliases: ['Effect on Capital Stock', 'Conversion of Securities', 'Merger Consideration'],
    frequency: 'universal',
    industries: [],
  },
  'CONSID-EXCHANGE': {
    type: 'CONSID',
    label: 'Exchange of Certificates / Payment Mechanics',
    description: 'Exchange fund, letter of transmittal, payment procedures',
    aliases: ['Exchange Fund', 'Payment for Shares', 'Exchange Procedures', 'Surrender of Certificates'],
    frequency: 'near-universal',
    industries: [],
  },
  'CONSID-EQUITY': {
    type: 'CONSID',
    label: 'Treatment of Equity Awards / Stock Plans',
    description: 'Treatment of outstanding options, RSUs, PSUs, warrants',
    aliases: ['Treatment of Stock Options', 'Treatment of RSUs', 'Company Equity Awards'],
    frequency: 'near-universal',
    industries: [],
  },
  'CONSID-DISSENT': {
    type: 'CONSID',
    label: 'Dissenting / Appraisal Rights',
    description: 'Treatment of shares held by dissenting stockholders',
    aliases: ['Appraisal Rights', 'Dissenters Rights'],
    frequency: 'common',
    industries: [],
  },
  'CONSID-WITHHOLD': {
    type: 'CONSID',
    label: 'Withholding Rights',
    description: 'Right to deduct and withhold taxes from merger consideration',
    aliases: ['Tax Withholding', 'Withholding'],
    frequency: 'common',
    industries: [],
  },
  'CONSID-ADJUST': {
    type: 'CONSID',
    label: 'Anti-Dilution Adjustments',
    description: 'Adjustments to consideration for stock splits, dividends, reclassifications',
    aliases: ['Adjustments', 'Anti-Dilution'],
    frequency: 'common',
    industries: [],
  },

  // ── REP-T ───────────────────────────────────────────────────────────────
  'REP-T-ORG': {
    type: 'REP-T',
    label: 'Organization; Qualification; Standing',
    description: 'Target is duly organized, validly existing, in good standing',
    aliases: ['Organization and Standing', 'Due Organization'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-CAP': {
    type: 'REP-T',
    label: 'Capitalization; Subsidiaries',
    description: 'Capital structure, outstanding shares, subsidiaries',
    aliases: ['Capitalization', 'Capital Stock'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-AUTH': {
    type: 'REP-T',
    label: 'Authority; Enforceability',
    description: 'Corporate authority to enter into and perform the agreement',
    aliases: ['Authority', 'Corporate Authority', 'Authority Relative to This Agreement'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-NOCONFLICT': {
    type: 'REP-T',
    label: 'No Conflict; Required Filings and Consents',
    description: 'No violation of charter, contracts, or laws; required governmental filings',
    aliases: ['Non-Contravention', 'No Violations', 'Consents and Approvals'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-SEC': {
    type: 'REP-T',
    label: 'SEC Documents; Financial Statements',
    description: 'SEC filings are complete and accurate; financial statements comply with GAAP',
    aliases: ['SEC Filings', 'SEC Reports', 'Reports and Financial Statements'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-T-FINSTMT': {
    type: 'REP-T',
    label: 'Financial Statements; No Liabilities (non-SEC filers)',
    description: 'Financial statements for companies that do not file with the SEC',
    aliases: ['Financial Statements'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-T-NOCHANGE': {
    type: 'REP-T',
    label: 'Absence of Certain Changes or Events',
    description: 'No material adverse change since the balance sheet date',
    aliases: ['Absence of Changes', 'No Material Adverse Change'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-NOLIAB': {
    type: 'REP-T',
    label: 'No Undisclosed Liabilities',
    description: 'No liabilities except as reflected in financial statements or disclosed',
    aliases: ['Undisclosed Liabilities'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-LIT': {
    type: 'REP-T',
    label: 'Litigation; Legal Proceedings',
    description: 'No pending or threatened litigation that would be material',
    aliases: ['Litigation', 'Legal Proceedings', 'Actions and Proceedings'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-COMPLY': {
    type: 'REP-T',
    label: 'Compliance with Laws; Permits; Licenses',
    description: 'Target is in compliance with applicable laws and holds required permits',
    aliases: ['Compliance with Laws', 'Permits and Licenses', 'Regulatory Compliance'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-BENEFITS': {
    type: 'REP-T',
    label: 'Employee Benefit Plans; ERISA',
    description: 'Employee benefit plans are listed, compliant with ERISA, properly funded',
    aliases: ['Employee Benefits', 'ERISA', 'Benefit Plans'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-T-LABOR': {
    type: 'REP-T',
    label: 'Labor Matters; Relations',
    description: 'Labor relations, collective bargaining, workforce matters',
    aliases: ['Labor Relations', 'Employment Matters', 'Labor and Employment'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-T-TAX': {
    type: 'REP-T',
    label: 'Taxes; Tax Returns',
    description: 'Tax returns filed, taxes paid, no material tax disputes',
    aliases: ['Taxes', 'Tax Matters'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-CONTRACTS': {
    type: 'REP-T',
    label: 'Material Contracts',
    description: 'Disclosure and status of material contracts',
    aliases: ['Contracts', 'Material Agreements'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-IP': {
    type: 'REP-T',
    label: 'Intellectual Property',
    description: 'Ownership and non-infringement of intellectual property',
    aliases: ['IP', 'Intellectual Property Rights'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-PROPERTY': {
    type: 'REP-T',
    label: 'Real Property; Personal Property; Title',
    description: 'Real and personal property ownership, leases, title',
    aliases: ['Real Property', 'Properties', 'Title to Assets'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-T-ENV': {
    type: 'REP-T',
    label: 'Environmental Matters',
    description: 'Compliance with environmental laws, no environmental liabilities',
    aliases: ['Environmental', 'Environmental Compliance'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-INSURANCE': {
    type: 'REP-T',
    label: 'Insurance',
    description: 'Insurance policies are in full force and effect',
    aliases: ['Insurance Policies', 'Insurance Coverage'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-BROKERS': {
    type: 'REP-T',
    label: 'Brokers; Finders',
    description: 'No brokers or finders fees except disclosed advisors',
    aliases: ['Brokers', 'Finders Fees'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-ANTICORR': {
    type: 'REP-T',
    label: 'Anti-Corruption; Sanctions',
    description: 'Compliance with FCPA, UK Bribery Act, anti-corruption laws',
    aliases: ['Anti-Corruption', 'FCPA', 'Bribery'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-PRIVACY': {
    type: 'REP-T',
    label: 'Data Privacy; Information Security; Cybersecurity',
    description: 'Compliance with privacy laws, data security measures',
    aliases: ['Data Privacy', 'Privacy', 'Cybersecurity', 'Information Security'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-TAKEOVER': {
    type: 'REP-T',
    label: 'Takeover Statutes; Anti-Takeover',
    description: 'Inapplicability of state anti-takeover statutes',
    aliases: ['Takeover Statutes', 'Anti-Takeover Provisions', 'State Takeover Laws'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-FAIRNESS': {
    type: 'REP-T',
    label: 'Opinion of Financial Advisor',
    description: 'Receipt of fairness opinion from financial advisor',
    aliases: ['Fairness Opinion', 'Financial Advisor Opinion'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-RPT': {
    type: 'REP-T',
    label: 'Related Party / Affiliate / Interested-Party Transactions',
    description: 'Disclosure of related party and affiliate transactions',
    aliases: ['Related Party Transactions', 'Affiliate Transactions', 'Interested Party Transactions'],
    frequency: 'universal',
    industries: [],
  },
  'REP-T-PROXY': {
    type: 'REP-T',
    label: 'Information Supplied / Proxy Statement',
    description: 'Information supplied for proxy statement is accurate',
    aliases: ['Information Supplied', 'Proxy Statement Information'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-NOREP': {
    type: 'REP-T',
    label: 'No Other Representations or Warranties',
    description: 'Disclaimer of representations beyond those expressly made',
    aliases: ['No Other Representations', 'Disclaimer of Representations'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-T-PRODUCT': {
    type: 'REP-T',
    label: 'Product Liability; Product Recall; Quality & Safety',
    description: 'Product liability claims, recalls, product quality and safety',
    aliases: ['Product Liability', 'Product Recall', 'Product Quality'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-SUPPLY': {
    type: 'REP-T',
    label: 'Suppliers',
    description: 'Key supplier relationships and status',
    aliases: ['Suppliers', 'Supply Chain'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'REP-T-FDA': {
    type: 'REP-T',
    label: 'FDA / Healthcare Regulatory',
    description: 'FDA compliance, healthcare regulatory status, product approvals',
    aliases: ['FDA Compliance', 'Healthcare Regulatory', 'FDA Matters'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'REP-T-CONTROLS': {
    type: 'REP-T',
    label: 'Internal Controls; Disclosure Controls',
    description: 'Effectiveness of internal controls over financial reporting',
    aliases: ['Internal Controls', 'Disclosure Controls', 'Sarbanes-Oxley'],
    frequency: 'common',
    industries: [],
  },
  'REP-T-SANCTIONS': {
    type: 'REP-T',
    label: 'Global Trade Control Laws; Sanctions',
    description: 'Compliance with sanctions, export controls, trade restrictions',
    aliases: ['Sanctions', 'Export Controls', 'Trade Controls'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'REP-T-OIL': {
    type: 'REP-T',
    label: 'Oil & Gas Leases; Rights-of-Way',
    description: 'Oil and gas lease interests, rights-of-way, surface rights',
    aliases: ['Oil and Gas Leases', 'Mineral Rights'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-T-WELLS': {
    type: 'REP-T',
    label: 'Wells and Equipment',
    description: 'Status of wells and related equipment',
    aliases: ['Wells', 'Drilling Equipment'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-T-RESERVE': {
    type: 'REP-T',
    label: 'Reserve Reports',
    description: 'Oil and gas reserve reports and estimates',
    aliases: ['Reserve Reports', 'Reserve Estimates'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-T-REGSTATUS': {
    type: 'REP-T',
    label: 'Regulatory Status',
    description: 'Regulatory status of the target company',
    aliases: ['Regulatory Status', 'Regulated Entity Status'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-T-CONSENT': {
    type: 'REP-T',
    label: 'Consents and Approvals (separate from No Conflict)',
    description: 'Standalone consents and approvals representation',
    aliases: ['Consents and Approvals'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  // Pharma-specific target reps (cross-check additions)
  'REP-T-CLINICAL': {
    type: 'REP-T',
    label: 'Clinical Trials; Clinical Data',
    description: 'Status of clinical trials, clinical data integrity, IND/NDA filings',
    aliases: ['Clinical Trials', 'Clinical Data', 'Clinical Studies'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'REP-T-HEALTHCARE': {
    type: 'REP-T',
    label: 'Healthcare Compliance',
    description: 'Compliance with healthcare laws including Anti-Kickback Statute, Stark Law, FCA',
    aliases: ['Healthcare Compliance', 'Anti-Kickback', 'Stark Law', 'False Claims Act'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'REP-T-HEALTHLAWS': {
    type: 'REP-T',
    label: 'Health Care Laws',
    description: 'Compliance with broader healthcare regulatory framework (HIPAA, state laws, PhRMA Code)',
    aliases: ['Health Care Laws', 'HIPAA Compliance', 'Healthcare Laws'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },

  // ── REP-B ───────────────────────────────────────────────────────────────
  'REP-B-ORG': {
    type: 'REP-B',
    label: 'Organization; Qualification; Standing',
    description: 'Buyer is duly organized, validly existing, in good standing',
    aliases: ['Organization and Standing'],
    frequency: 'universal',
    industries: [],
  },
  'REP-B-AUTH': {
    type: 'REP-B',
    label: 'Authority; Enforceability',
    description: 'Buyer has corporate authority to enter into and perform the agreement',
    aliases: ['Authority', 'Corporate Authority'],
    frequency: 'universal',
    industries: [],
  },
  'REP-B-NOCONFLICT': {
    type: 'REP-B',
    label: 'No Conflict; Required Filings and Consents',
    description: 'No violation of buyer charter, contracts, or laws',
    aliases: ['Non-Contravention', 'No Violations'],
    frequency: 'universal',
    industries: [],
  },
  'REP-B-LIT': {
    type: 'REP-B',
    label: 'Litigation; Legal Proceedings',
    description: 'No pending or threatened litigation against buyer that would impede the merger',
    aliases: ['Litigation', 'Legal Proceedings'],
    frequency: 'universal',
    industries: [],
  },
  'REP-B-BROKERS': {
    type: 'REP-B',
    label: 'Brokers; Finders',
    description: 'No brokers or finders fees payable by buyer except disclosed advisors',
    aliases: ['Brokers', 'Finders Fees'],
    frequency: 'universal',
    industries: [],
  },
  'REP-B-FUNDS': {
    type: 'REP-B',
    label: 'Sufficient / Available Funds; Financing',
    description: 'Buyer has sufficient funds or committed financing to pay merger consideration',
    aliases: ['Available Funds', 'Financing', 'Sufficient Funds'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-B-MERGESUB': {
    type: 'REP-B',
    label: 'Merger Sub; No Prior Activities',
    description: 'Merger sub is newly formed with no prior operations',
    aliases: ['Merger Sub', 'No Prior Activities'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-PROXY': {
    type: 'REP-B',
    label: 'Information Supplied / Proxy Statement',
    description: 'Information supplied by buyer for proxy statement is accurate',
    aliases: ['Information Supplied', 'Proxy Statement Information'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-VOTE': {
    type: 'REP-B',
    label: 'Vote / Approval Required',
    description: 'No buyer stockholder vote required for the merger',
    aliases: ['No Vote Required', 'Buyer Stockholder Approval'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-NOINTEREST': {
    type: 'REP-B',
    label: 'No Interested Stockholder; Ownership of Stock',
    description: 'Buyer does not own target stock triggering anti-takeover statutes',
    aliases: ['No Interested Stockholder', 'Ownership of Company Stock'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-NOREP': {
    type: 'REP-B',
    label: 'No Other Representations or Warranties',
    description: 'Disclaimer of buyer representations beyond those expressly made',
    aliases: ['No Other Representations', 'Disclaimer of Representations'],
    frequency: 'near-universal',
    industries: [],
  },
  'REP-B-CAP': {
    type: 'REP-B',
    label: 'Capitalization (public buyer)',
    description: 'Buyer capital structure for stock-deal transactions',
    aliases: ['Buyer Capitalization'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-SEC': {
    type: 'REP-B',
    label: 'SEC Documents; Financial Statements (public buyer)',
    description: 'Buyer SEC filings and financial statements',
    aliases: ['Buyer SEC Filings', 'Buyer Financial Statements'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-NOCHANGE': {
    type: 'REP-B',
    label: 'Absence of Certain Changes (public buyer)',
    description: 'No material adverse change in buyer since balance sheet date',
    aliases: ['Buyer Absence of Changes'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-NOLIAB': {
    type: 'REP-B',
    label: 'No Undisclosed Liabilities (public buyer)',
    description: 'No undisclosed liabilities of buyer',
    aliases: ['Buyer Undisclosed Liabilities'],
    frequency: 'industry-specific',
    industries: [],
  },
  'REP-B-TAX': {
    type: 'REP-B',
    label: 'Taxes (public buyer)',
    description: 'Buyer tax representations for stock-deal transactions',
    aliases: ['Buyer Taxes'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-COMPLY': {
    type: 'REP-B',
    label: 'Compliance with Laws (public buyer)',
    description: 'Buyer compliance with applicable laws',
    aliases: ['Buyer Compliance'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-BENEFITS': {
    type: 'REP-B',
    label: 'Employee Benefit Plans (public buyer)',
    description: 'Buyer employee benefit plan representations',
    aliases: ['Buyer Employee Benefits'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-ENV': {
    type: 'REP-B',
    label: 'Environmental (public buyer)',
    description: 'Buyer environmental compliance representations',
    aliases: ['Buyer Environmental'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-B-IP': {
    type: 'REP-B',
    label: 'Intellectual Property (public buyer)',
    description: 'Buyer intellectual property representations',
    aliases: ['Buyer IP', 'Buyer Intellectual Property'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-B-CONTRACTS': {
    type: 'REP-B',
    label: 'Material Contracts (public buyer)',
    description: 'Buyer material contract representations',
    aliases: ['Buyer Material Contracts'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },
  'REP-B-SOLVENCY': {
    type: 'REP-B',
    label: 'Solvency',
    description: 'Buyer is and will remain solvent after the merger',
    aliases: ['Solvency', 'Solvency Opinion'],
    frequency: 'industry-specific',
    industries: [],
  },
  'REP-B-LABOR': {
    type: 'REP-B',
    label: 'Labor Matters (public buyer)',
    description: 'Buyer labor and employment representations',
    aliases: ['Buyer Labor', 'Buyer Employment'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-EQUITY': {
    type: 'REP-B',
    label: 'Equity Investment',
    description: 'Representations regarding equity investment in the transaction',
    aliases: ['Equity Investment'],
    frequency: 'industry-specific',
    industries: [],
  },
  'REP-B-FAIRNESS': {
    type: 'REP-B',
    label: 'Opinion of Financial Advisor (buyer)',
    description: 'Buyer receipt of fairness opinion',
    aliases: ['Buyer Fairness Opinion'],
    frequency: 'common',
    industries: [],
  },
  'REP-B-NORIGHTS': {
    type: 'REP-B',
    label: 'No Rights Plan',
    description: 'Buyer has no poison pill or rights plan in effect',
    aliases: ['No Rights Plan', 'No Poison Pill'],
    frequency: 'industry-specific',
    industries: ['energy'],
  },

  // ── IOC ─────────────────────────────────────────────────────────────────
  'IOC-ORDINARY': {
    type: 'IOC',
    label: 'Ordinary Course Obligation',
    description: 'General obligation to conduct business in the ordinary course',
    aliases: ['Ordinary Course', 'Conduct of Business'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-CHARTER': {
    type: 'IOC',
    label: 'Charter / Bylaws Amendments',
    description: 'No amendments to certificate of incorporation or bylaws',
    aliases: ['Charter Amendments', 'Bylaws Amendments', 'Organizational Document Changes'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-MERGE': {
    type: 'IOC',
    label: 'Mergers, Acquisitions, Dispositions',
    description: 'No mergers, acquisitions, sales of material assets',
    aliases: ['No Acquisitions', 'No Dispositions', 'Asset Sales'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-ISSUE': {
    type: 'IOC',
    label: 'Issuance of Securities',
    description: 'No issuance, sale, or pledge of equity securities',
    aliases: ['No Issuance of Securities', 'Securities Issuance'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-REPURCHASE': {
    type: 'IOC',
    label: 'Share Repurchases',
    description: 'No repurchase or redemption of equity securities',
    aliases: ['No Share Repurchases', 'No Redemptions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-DIVIDEND': {
    type: 'IOC',
    label: 'Dividends and Distributions',
    description: 'No declaration or payment of dividends',
    aliases: ['No Dividends', 'No Distributions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-SPLIT': {
    type: 'IOC',
    label: 'Stock Splits / Reclassifications',
    description: 'No splits, combinations, subdivisions, reclassifications',
    aliases: ['No Stock Splits', 'No Reclassifications'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-DEBT': {
    type: 'IOC',
    label: 'Indebtedness',
    description: 'No incurrence of indebtedness or guarantees',
    aliases: ['No Indebtedness', 'No Borrowing', 'No Guarantees'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-LIEN': {
    type: 'IOC',
    label: 'Liens and Encumbrances',
    description: 'No creation of liens on material assets',
    aliases: ['No Liens', 'No Encumbrances'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-CAPEX': {
    type: 'IOC',
    label: 'Capital Expenditures',
    description: 'Restrictions on capital expenditures',
    aliases: ['CapEx Restrictions', 'Capital Spending'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-COMP': {
    type: 'IOC',
    label: 'Compensation and Benefits',
    description: 'No increases in compensation, bonuses, new plans',
    aliases: ['No Compensation Increases', 'No Bonus Payments', 'Compensation Changes'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-HIRE': {
    type: 'IOC',
    label: 'Hiring and Termination',
    description: 'Restrictions on hiring/firing above certain levels',
    aliases: ['Hiring Restrictions', 'Termination Restrictions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-SETTLE': {
    type: 'IOC',
    label: 'Settlement of Claims',
    description: 'No settlement of material litigation',
    aliases: ['No Settlements', 'Litigation Settlement'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-TAX': {
    type: 'IOC',
    label: 'Tax Elections and Filings',
    description: 'No material changes in tax elections, methods, or filings',
    aliases: ['Tax Elections', 'No Tax Changes'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-ACCOUNTING': {
    type: 'IOC',
    label: 'Accounting Changes',
    description: 'No changes in accounting methods or principles',
    aliases: ['No Accounting Changes', 'Accounting Methods'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-CONTRACT': {
    type: 'IOC',
    label: 'Material Contracts',
    description: 'No entry into, modification, or termination of material contracts',
    aliases: ['No Contract Changes', 'Material Contract Restrictions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-IP': {
    type: 'IOC',
    label: 'Intellectual Property',
    description: 'No licensing, transfer, or abandonment of material IP',
    aliases: ['No IP Transfers', 'IP Restrictions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-INSURANCE': {
    type: 'IOC',
    label: 'Insurance Policies',
    description: 'No cancellation or material change to insurance',
    aliases: ['No Insurance Changes'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-REALPROP': {
    type: 'IOC',
    label: 'Real Property',
    description: 'No acquisition, sale, or lease of real property',
    aliases: ['No Real Property Changes', 'Real Estate Restrictions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-WAIVE': {
    type: 'IOC',
    label: 'Waiver of Rights',
    description: 'No waiver or release of material claims or rights',
    aliases: ['No Waivers', 'No Release of Rights'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-AFFILIATE': {
    type: 'IOC',
    label: 'Affiliate Transactions',
    description: 'No entry into transactions with affiliates',
    aliases: ['No Affiliate Transactions', 'Related Party Restrictions'],
    frequency: 'universal',
    industries: [],
  },
  'IOC-ENVIRO': {
    type: 'IOC',
    label: 'Environmental',
    description: 'No actions that would create material environmental liability',
    aliases: ['Environmental Restrictions'],
    frequency: 'common',
    industries: [],
  },
  'IOC-COMMIT': {
    type: 'IOC',
    label: 'Commitments',
    description: 'No agreement or commitment to do any of the foregoing',
    aliases: ['No Commitments', 'Anti-Evasion'],
    frequency: 'universal',
    industries: [],
  },
  // Pharma-specific IOC (cross-check additions)
  'IOC-CLINICAL': {
    type: 'IOC',
    label: 'Clinical Trials',
    description: 'Restrictions on initiating, modifying, or terminating clinical trials',
    aliases: ['Clinical Trial Restrictions', 'No Clinical Trial Changes'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'IOC-PRODUCT': {
    type: 'IOC',
    label: 'Product Development',
    description: 'Restrictions on product development, formulation changes, manufacturing process changes',
    aliases: ['Product Development Restrictions', 'No Product Changes'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'IOC-REGAUTH': {
    type: 'IOC',
    label: 'Regulatory Authorizations',
    description: 'Restrictions on withdrawing, modifying, or failing to maintain regulatory authorizations',
    aliases: ['Regulatory Authorization Restrictions', 'No Regulatory Changes'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },

  // ── NOSOL ───────────────────────────────────────────────────────────────
  'NOSOL-PROHIBIT': {
    type: 'NOSOL',
    label: 'Solicitation Prohibition',
    description: 'Core no-shop / no-solicitation restriction',
    aliases: ['No-Shop', 'No-Solicitation', 'Non-Solicitation'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-CEASE': {
    type: 'NOSOL',
    label: 'Cease Existing Discussions',
    description: 'Obligation to cease and terminate pre-signing discussions',
    aliases: ['Cease Discussions', 'Terminate Existing Negotiations'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-EXCEPT': {
    type: 'NOSOL',
    label: 'Exceptions / Fiduciary Out',
    description: 'Conditions under which board may engage with unsolicited proposals',
    aliases: ['Fiduciary Out', 'Fiduciary Exception', 'Board Exception'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-SUPERIOR': {
    type: 'NOSOL',
    label: 'Superior Proposal Definition',
    description: 'Definition and criteria for what constitutes a "superior proposal"',
    aliases: ['Superior Proposal', 'Superior Offer'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-ACQPROPOSAL': {
    type: 'NOSOL',
    label: 'Acquisition Proposal Definition',
    description: 'Definition of "acquisition proposal" / "competing proposal"',
    aliases: ['Acquisition Proposal', 'Competing Proposal', 'Takeover Proposal'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-NOTICE': {
    type: 'NOSOL',
    label: 'Notice to Counterparty',
    description: 'Obligation to promptly notify buyer of receipt of competing proposals',
    aliases: ['Notice of Competing Proposal', 'Notification Obligation'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-DISCLOSE': {
    type: 'NOSOL',
    label: 'Disclosure of Terms',
    description: 'Obligation to share identity of bidder and material terms of proposals',
    aliases: ['Disclosure of Bidder Identity', 'Sharing of Proposal Terms'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-MATCH': {
    type: 'NOSOL',
    label: 'Matching Rights',
    description: 'Buyer\'s right to match or improve offer before board acts',
    aliases: ['Right to Match', 'Matching Right', 'Last Look'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-NEGOTIATE': {
    type: 'NOSOL',
    label: 'Negotiation Period',
    description: 'Specific time period for buyer to negotiate/match (e.g. 4 business days)',
    aliases: ['Negotiation Period', 'Matching Period'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-REMATCH': {
    type: 'NOSOL',
    label: 'Subsequent Matching / Amendment Rights',
    description: 'Re-matching rights on material amendments to competing proposal',
    aliases: ['Subsequent Matching', 'Re-Match Rights', 'Amendment Matching'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-RECOMMEND': {
    type: 'NOSOL',
    label: 'Change of Recommendation',
    description: 'Board\'s right and process to withdraw or change its recommendation',
    aliases: ['Change of Recommendation', 'Recommendation Withdrawal', 'Adverse Recommendation Change'],
    frequency: 'universal',
    industries: [],
  },
  'NOSOL-INTERVENING': {
    type: 'NOSOL',
    label: 'Intervening Event',
    description: 'Rights related to intervening events distinct from competing proposals',
    aliases: ['Intervening Event', 'Intervening Event Exception'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-WINDOW': {
    type: 'NOSOL',
    label: 'Go-Shop / Window Shop',
    description: 'Active solicitation window period (if any); post-window transition',
    aliases: ['Go-Shop', 'Window Shop', 'Go-Shop Period', 'Active Solicitation Period'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-ENFORCE': {
    type: 'NOSOL',
    label: 'Enforcement of Standstills',
    description: 'Obligation to enforce or not waive existing standstill/NDA obligations',
    aliases: ['Standstill Enforcement', 'NDA Enforcement'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-WAIVER': {
    type: 'NOSOL',
    label: 'Standstill Waiver / Don\'t-Ask-Don\'t-Waive',
    description: 'Whether target can waive standstills; DADW provisions',
    aliases: ['DADW', 'Don\'t Ask Don\'t Waive', 'Standstill Waiver'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-INFORMATION': {
    type: 'NOSOL',
    label: 'Provision of Information to Bidder',
    description: 'Conditions for providing non-public information to a third-party bidder',
    aliases: ['Information Rights', 'Data Room Access for Bidders'],
    frequency: 'common',
    industries: [],
  },
  'NOSOL-CONFID': {
    type: 'NOSOL',
    label: 'Confidentiality Agreement Requirement',
    description: 'Requirement for acceptable confidentiality agreement with bidder',
    aliases: ['NDA Requirement', 'Confidentiality Requirement'],
    frequency: 'common',
    industries: [],
  },

  // ── ANTI ────────────────────────────────────────────────────────────────
  'ANTI-FILING': {
    type: 'ANTI',
    label: 'HSR / Regulatory Filings',
    description: 'Obligation to promptly make HSR and other antitrust filings',
    aliases: ['HSR Filing', 'Antitrust Filing', 'Regulatory Filing'],
    frequency: 'universal',
    industries: [],
  },
  'ANTI-EFFORTS': {
    type: 'ANTI',
    label: 'Standard of Efforts',
    description: 'Efforts standard — reasonable best efforts, commercially reasonable, etc.',
    aliases: ['Best Efforts', 'Reasonable Best Efforts', 'Commercially Reasonable Efforts'],
    frequency: 'near-universal',
    industries: [],
  },
  'ANTI-COOPERATE': {
    type: 'ANTI',
    label: 'Cooperation',
    description: 'Mutual cooperation obligations in dealing with regulators',
    aliases: ['Regulatory Cooperation', 'Mutual Cooperation'],
    frequency: 'universal',
    industries: [],
  },
  'ANTI-INFO': {
    type: 'ANTI',
    label: 'Information to Regulators',
    description: 'Obligation to provide information and documents to regulators',
    aliases: ['Information Provision', 'Document Production'],
    frequency: 'universal',
    industries: [],
  },
  'ANTI-BURDEN': {
    type: 'ANTI',
    label: 'Burden Cap / Divestiture Limits',
    description: 'Limits on required divestitures, hold-separates, behavioral remedies; hell-or-high-water is the absence of any such cap',
    aliases: ['Divestiture Cap', 'Hold-Separate', 'Hell or High Water', 'Burdensome Condition'],
    frequency: 'near-universal',
    industries: [],
  },
  'ANTI-NOACTION': {
    type: 'ANTI',
    label: 'No Inconsistent Action',
    description: 'Prohibition on actions that would impede or delay regulatory clearance',
    aliases: ['No Inconsistent Action', 'No Impediment'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-FOREIGN': {
    type: 'ANTI',
    label: 'Foreign Regulatory Approvals',
    description: 'Non-US antitrust/regulatory filings and approvals (EU, China, etc.)',
    aliases: ['Foreign Antitrust', 'EU Merger Filing', 'CFIUS', 'International Regulatory'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-INTERIM': {
    type: 'ANTI',
    label: 'Interim Compliance',
    description: 'Operating restrictions during regulatory review period',
    aliases: ['Interim Operating Restrictions', 'Regulatory Review Period'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-NOTIFY': {
    type: 'ANTI',
    label: 'Notification of Developments',
    description: 'Obligation to notify counterparty of material regulatory developments',
    aliases: ['Regulatory Notification', 'Notice of Developments'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-LITIGATION': {
    type: 'ANTI',
    label: 'Litigation Against Regulators',
    description: 'Obligation (or right) to litigate/challenge adverse regulatory action',
    aliases: ['Regulatory Litigation', 'Challenge Regulatory Action'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-CONSULT': {
    type: 'ANTI',
    label: 'Consultation Rights',
    description: 'Right to review and comment on filings and communications with regulators',
    aliases: ['Filing Review', 'Consultation on Filings'],
    frequency: 'common',
    industries: [],
  },
  'ANTI-TIMING': {
    type: 'ANTI',
    label: 'Timing Agreements',
    description: 'Agreements on timing of filings, pull-and-refile, extensions',
    aliases: ['Filing Timing', 'Pull and Refile'],
    frequency: 'common',
    industries: [],
  },

  // ── COND-M ──────────────────────────────────────────────────────────────
  'COND-M-LEGAL': {
    type: 'COND-M',
    label: 'No Legal Impediment',
    description: 'No injunction, order, or law preventing closing',
    aliases: ['No Injunction', 'No Legal Bar', 'No Legal Impediment'],
    frequency: 'near-universal',
    industries: [],
  },
  'COND-M-REG': {
    type: 'COND-M',
    label: 'Regulatory Approvals',
    description: 'HSR expiration/termination and other required regulatory approvals',
    aliases: ['HSR Clearance', 'Antitrust Approval', 'Regulatory Clearance'],
    frequency: 'universal',
    industries: [],
  },
  'COND-M-STOCKHOLDER': {
    type: 'COND-M',
    label: 'Stockholder Approval',
    description: 'Company stockholder vote obtained',
    aliases: ['Stockholder Vote', 'Shareholder Approval'],
    frequency: 'near-universal',
    industries: [],
  },
  'COND-M-S4': {
    type: 'COND-M',
    label: 'Form S-4 Effectiveness',
    description: 'Registration statement effective (stock deals)',
    aliases: ['S-4 Effective', 'Registration Statement'],
    frequency: 'common',
    industries: [],
  },
  'COND-M-LISTING': {
    type: 'COND-M',
    label: 'Stock Exchange Listing',
    description: 'Buyer shares approved for listing (stock deals)',
    aliases: ['Listing Approval', 'NYSE Listing', 'NASDAQ Listing'],
    frequency: 'common',
    industries: [],
  },

  // ── COND-B ──────────────────────────────────────────────────────────────
  'COND-B-REP': {
    type: 'COND-B',
    label: 'Accuracy of Target Reps',
    description: 'Target\'s representations are true and correct (at specified standard)',
    aliases: ['Target Reps Accurate', 'Company Reps Bring-Down'],
    frequency: 'universal',
    industries: [],
  },
  'COND-B-COV': {
    type: 'COND-B',
    label: 'Target Covenant Compliance',
    description: 'Target has performed its covenants in all material respects',
    aliases: ['Target Covenant Compliance', 'Company Covenant Bring-Down'],
    frequency: 'universal',
    industries: [],
  },
  'COND-B-MAE': {
    type: 'COND-B',
    label: 'No Target MAE',
    description: 'No material adverse effect on the target since signing',
    aliases: ['No MAE', 'No Material Adverse Effect', 'MAE Condition'],
    frequency: 'universal',
    industries: [],
  },
  'COND-B-CERT': {
    type: 'COND-B',
    label: 'Officer\'s Certificate (Target)',
    description: 'Delivery of target officer\'s certificate confirming reps/covenants',
    aliases: ['Target Officer Certificate', 'Company Closing Certificate'],
    frequency: 'universal',
    industries: [],
  },
  'COND-B-DISSENT': {
    type: 'COND-B',
    label: 'Dissenting Shares Threshold',
    description: 'Dissenting shares below specified threshold (if applicable)',
    aliases: ['Dissenting Shares Condition', 'Appraisal Threshold'],
    frequency: 'industry-specific',
    industries: [],
  },

  // ── COND-S ──────────────────────────────────────────────────────────────
  'COND-S-REP': {
    type: 'COND-S',
    label: 'Accuracy of Buyer Reps',
    description: 'Buyer\'s representations are true and correct (at specified standard)',
    aliases: ['Buyer Reps Accurate', 'Parent Reps Bring-Down'],
    frequency: 'universal',
    industries: [],
  },
  'COND-S-COV': {
    type: 'COND-S',
    label: 'Buyer Covenant Compliance',
    description: 'Buyer has performed its covenants in all material respects',
    aliases: ['Buyer Covenant Compliance', 'Parent Covenant Bring-Down'],
    frequency: 'universal',
    industries: [],
  },
  'COND-S-CERT': {
    type: 'COND-S',
    label: 'Officer\'s Certificate (Buyer)',
    description: 'Delivery of buyer officer\'s certificate confirming reps/covenants',
    aliases: ['Buyer Officer Certificate', 'Parent Closing Certificate'],
    frequency: 'universal',
    industries: [],
  },
  'COND-S-FUNDS': {
    type: 'COND-S',
    label: 'Availability of Funds',
    description: 'Buyer has funds available to pay merger consideration',
    aliases: ['Funds Condition', 'Financing Condition'],
    frequency: 'common',
    industries: [],
  },

  // ── COND (modifiers) ───────────────────────────────────────────────────
  'COND-FRUSTRATE': {
    type: 'COND',
    label: 'Frustration of Conditions',
    description: 'Party cannot invoke failure of condition it caused',
    aliases: ['Anti-Frustration', 'No Frustration'],
    frequency: 'common',
    industries: [],
  },
  'COND-TAXOPINION': {
    type: 'COND',
    label: 'Tax Opinion',
    description: 'Receipt of required tax opinions as condition',
    aliases: ['Tax Opinion Condition', 'Tax-Free Reorganization Opinion'],
    frequency: 'common',
    industries: [],
  },

  // ── TERMR ───────────────────────────────────────────────────────────────
  'TERMR-MUTUAL': {
    type: 'TERMR',
    label: 'Mutual Termination',
    description: 'Termination by mutual written consent',
    aliases: ['Mutual Consent Termination'],
    frequency: 'near-universal',
    industries: [],
  },
  'TERMR-OUTSIDE': {
    type: 'TERMR',
    label: 'Outside Date',
    description: 'Termination if closing hasn\'t occurred by outside date',
    aliases: ['Outside Date', 'End Date', 'Drop Dead Date', 'Long Stop Date'],
    frequency: 'near-universal',
    industries: [],
  },
  'TERMR-EXTENSION': {
    type: 'TERMR',
    label: 'Outside Date Extension',
    description: 'Automatic or optional extension of the outside date',
    aliases: ['Extension of Outside Date', 'Ticking Fee'],
    frequency: 'common',
    industries: [],
  },
  'TERMR-LEGAL': {
    type: 'TERMR',
    label: 'Legal Impediment',
    description: 'Termination due to final, non-appealable injunction or legal bar',
    aliases: ['Legal Bar Termination', 'Injunction Termination'],
    frequency: 'common',
    industries: [],
  },
  'TERMR-VOTE': {
    type: 'TERMR',
    label: 'Stockholder Vote Failure',
    description: 'Termination if stockholder approval not obtained at meeting',
    aliases: ['Vote Failure Termination', 'Failed Stockholder Vote'],
    frequency: 'common',
    industries: [],
  },
  'TERMR-BREACH-T': {
    type: 'TERMR',
    label: 'Target Breach',
    description: 'Buyer\'s right to terminate for target\'s uncured material breach',
    aliases: ['Target Breach Termination', 'Company Breach'],
    frequency: 'universal',
    industries: [],
  },
  'TERMR-BREACH-B': {
    type: 'TERMR',
    label: 'Buyer Breach',
    description: 'Target\'s right to terminate for buyer\'s uncured material breach',
    aliases: ['Buyer Breach Termination', 'Parent Breach'],
    frequency: 'universal',
    industries: [],
  },
  'TERMR-SUPERIOR': {
    type: 'TERMR',
    label: 'Superior Proposal',
    description: 'Target\'s right to terminate to accept a superior proposal',
    aliases: ['Superior Proposal Termination', 'Fiduciary Termination'],
    frequency: 'common',
    industries: [],
  },
  'TERMR-RECOMMEND': {
    type: 'TERMR',
    label: 'Change of Recommendation',
    description: 'Buyer\'s right to terminate upon target board\'s change of recommendation',
    aliases: ['Change of Recommendation Termination', 'Adverse Recommendation Termination'],
    frequency: 'common',
    industries: [],
  },

  // ── TERMF ───────────────────────────────────────────────────────────────
  'TERMF-TARGET': {
    type: 'TERMF',
    label: 'Company Termination Fee',
    description: 'Fee payable by the target company (amount and trigger)',
    aliases: ['Target Termination Fee', 'Company Break-Up Fee', 'Break Fee'],
    frequency: 'universal',
    industries: [],
  },
  'TERMF-REVERSE': {
    type: 'TERMF',
    label: 'Reverse Termination Fee',
    description: 'Fee payable by the buyer (amount and trigger)',
    aliases: ['Reverse Break-Up Fee', 'Buyer Termination Fee', 'Reverse Break Fee'],
    frequency: 'common',
    industries: [],
  },
  'TERMF-EXPENSE': {
    type: 'TERMF',
    label: 'Expense Reimbursement',
    description: 'Expense reimbursement obligations on termination',
    aliases: ['Termination Expense Reimbursement'],
    frequency: 'common',
    industries: [],
  },
  'TERMF-TAIL': {
    type: 'TERMF',
    label: 'Tail Provision',
    description: 'Fee triggered by subsequent alternative transaction within specified period',
    aliases: ['Tail Period', 'Naked No-Vote Fee', 'Subsequent Transaction Fee'],
    frequency: 'common',
    industries: [],
  },
  'TERMF-EFFECT': {
    type: 'TERMF',
    label: 'Effect of Termination',
    description: 'Consequences and limitations on liability post-termination',
    aliases: ['Effect of Termination', 'Post-Termination Liability'],
    frequency: 'universal',
    industries: [],
  },
  'TERMF-SOLE': {
    type: 'TERMF',
    label: 'Sole and Exclusive Remedy',
    description: 'Fee as sole remedy / liability cap provision',
    aliases: ['Sole Remedy', 'Exclusive Remedy', 'Liability Cap'],
    frequency: 'common',
    industries: [],
  },

  // ── DEF ─────────────────────────────────────────────────────────────────
  // Core Negotiated Definitions
  'DEF-MAE': {
    type: 'DEF',
    label: 'Material Adverse Effect',
    description: 'Core MAE definition — what constitutes an MAE on the company',
    aliases: ['MAE', 'Material Adverse Change', 'MAC'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-MAE-CARVEOUT': {
    type: 'DEF',
    label: 'MAE Carve-Outs',
    description: 'Enumerated exceptions (market conditions, industry changes, law changes, etc.)',
    aliases: ['MAE Exceptions', 'MAE Exclusions', 'Carve-Outs'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-MAE-DISPROP': {
    type: 'DEF',
    label: 'MAE Disproportionate Impact',
    description: '"Except to the extent disproportionately affected" qualifier on carve-outs',
    aliases: ['Disproportionate Impact', 'Disproportionate Effect'],
    frequency: 'common',
    industries: [],
  },
  // Pharma-specific MAE definition (cross-check addition)
  'DEF-MAE-CLINICAL': {
    type: 'DEF',
    label: 'MAE Clinical Exclusion',
    description: 'MAE carve-out or inclusion for clinical trial results, FDA actions, or pipeline developments',
    aliases: ['Clinical Trial MAE Carve-Out', 'FDA Action MAE', 'Pipeline MAE'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  'DEF-SUPERIOR': {
    type: 'DEF',
    label: 'Superior Proposal',
    description: 'Definition of what constitutes a "superior proposal"',
    aliases: ['Superior Proposal Definition', 'Superior Offer Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-ACQPROPOSAL': {
    type: 'DEF',
    label: 'Acquisition Proposal',
    description: 'Definition of "acquisition proposal" / "takeover proposal" / "competing transaction"',
    aliases: ['Acquisition Proposal Definition', 'Competing Transaction', 'Takeover Proposal Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-INTERVENING': {
    type: 'DEF',
    label: 'Intervening Event',
    description: 'Definition of "intervening event" (if the concept exists in the deal)',
    aliases: ['Intervening Event Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-KNOWLEDGE': {
    type: 'DEF',
    label: 'Knowledge',
    description: 'Knowledge standard — actual knowledge, constructive knowledge, inquiry obligation',
    aliases: ['Knowledge Qualifier', 'Knowledge Standard', 'To the Knowledge of'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-ORDINARY': {
    type: 'DEF',
    label: 'Ordinary Course of Business',
    description: 'Meaning of "ordinary course" and any "consistent with past practice" qualifier',
    aliases: ['Ordinary Course', 'Consistent with Past Practice'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-BURDENSOME': {
    type: 'DEF',
    label: 'Burdensome Condition',
    description: 'Definition of what constitutes a "burdensome condition" for regulatory remedies',
    aliases: ['Burdensome Condition Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-WILLFUL': {
    type: 'DEF',
    label: 'Willful Breach',
    description: 'Definition of "willful breach" or "intentional breach" (impacts liability caps)',
    aliases: ['Willful Breach Definition', 'Intentional Breach', 'Knowing and Intentional Breach'],
    frequency: 'common',
    industries: [],
  },
  // Structural / Entity Definitions
  'DEF-SUBSIDIARY': {
    type: 'DEF',
    label: 'Subsidiary',
    description: 'Definition of subsidiary and what entities are included',
    aliases: ['Subsidiary Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-AFFILIATE': {
    type: 'DEF',
    label: 'Affiliate',
    description: 'Definition of affiliate',
    aliases: ['Affiliate Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-PERSON': {
    type: 'DEF',
    label: 'Person',
    description: 'Definition of person (natural persons, entities, governmental authorities)',
    aliases: ['Person Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-REPRESENTATIVE': {
    type: 'DEF',
    label: 'Representatives',
    description: 'Definition of who constitutes "representatives" (advisors, agents, etc.)',
    aliases: ['Representatives Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-COMPANY': {
    type: 'DEF',
    label: 'Company / Target',
    description: 'Definition of the target entity and its coverage',
    aliases: ['Company Definition', 'Target Definition'],
    frequency: 'universal',
    industries: [],
  },
  // Financial / Contractual Definitions
  'DEF-LIEN': {
    type: 'DEF',
    label: 'Lien',
    description: 'Definition of lien, mortgage, pledge, encumbrance',
    aliases: ['Lien Definition', 'Encumbrance Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-PERMITLIEN': {
    type: 'DEF',
    label: 'Permitted Liens',
    description: 'Exceptions to lien restrictions (statutory liens, tax liens, etc.)',
    aliases: ['Permitted Liens Definition', 'Permitted Encumbrances'],
    frequency: 'common',
    industries: [],
  },
  'DEF-CONTRACT': {
    type: 'DEF',
    label: 'Contract',
    description: 'What constitutes a "contract" under the agreement',
    aliases: ['Contract Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-MATCONTRACT': {
    type: 'DEF',
    label: 'Material Contract',
    description: 'Criteria for what makes a contract "material"',
    aliases: ['Material Contract Definition', 'Material Agreement'],
    frequency: 'common',
    industries: [],
  },
  'DEF-INDEBTEDNESS': {
    type: 'DEF',
    label: 'Indebtedness',
    description: 'Definition of indebtedness for covenant and condition purposes',
    aliases: ['Indebtedness Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-BUSINESSDAY': {
    type: 'DEF',
    label: 'Business Day',
    description: 'Business day definition (jurisdiction, exclusions)',
    aliases: ['Business Day Definition'],
    frequency: 'universal',
    industries: [],
  },
  // Securities & Equity Definitions
  'DEF-MERGERCONSID': {
    type: 'DEF',
    label: 'Merger Consideration',
    description: 'Definition of the consideration payable per share',
    aliases: ['Per Share Merger Consideration', 'Aggregate Merger Consideration', 'Closing Consideration'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-EQUITYAWARD': {
    type: 'DEF',
    label: 'Company Equity Awards',
    description: 'What equity instruments are covered (options, RSUs, PSUs, warrants)',
    aliases: ['Equity Award Definition', 'Stock Option Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-DISSENTING': {
    type: 'DEF',
    label: 'Dissenting Shares',
    description: 'Definition and treatment of dissenting/appraisal shares',
    aliases: ['Dissenting Shares Definition', 'Appraisal Shares'],
    frequency: 'common',
    industries: [],
  },
  // Regulatory Definitions
  'DEF-GOVAUTH': {
    type: 'DEF',
    label: 'Governmental Authority',
    description: 'What bodies constitute a governmental authority',
    aliases: ['Governmental Authority Definition', 'Government Body'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-LAW': {
    type: 'DEF',
    label: 'Law',
    description: 'Definition of "law" (statutes, regulations, orders, etc.)',
    aliases: ['Law Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-PERMIT': {
    type: 'DEF',
    label: 'Permit',
    description: 'Definition of permits, licenses, authorizations',
    aliases: ['Permit Definition', 'License Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-REQUIREDAPPROVAL': {
    type: 'DEF',
    label: 'Required Approvals',
    description: 'Specific regulatory approvals needed for closing',
    aliases: ['Required Approvals Definition', 'Required Consents'],
    frequency: 'common',
    industries: [],
  },
  // Employee / Benefits Definitions
  'DEF-BENEFITPLAN': {
    type: 'DEF',
    label: 'Company Benefit Plan',
    description: 'What employee plans are covered',
    aliases: ['Benefit Plan Definition', 'Employee Plan Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-COMPANYEMPLOYEE': {
    type: 'DEF',
    label: 'Company Employees',
    description: 'Which employees are covered by post-closing obligations',
    aliases: ['Company Employee Definition', 'Covered Employees'],
    frequency: 'common',
    industries: [],
  },
  // Tax Definitions
  'DEF-TAX': {
    type: 'DEF',
    label: 'Tax / Taxes',
    description: 'Definition of taxes',
    aliases: ['Tax Definition'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-TAXRETURN': {
    type: 'DEF',
    label: 'Tax Return',
    description: 'Definition of tax returns',
    aliases: ['Tax Return Definition'],
    frequency: 'common',
    industries: [],
  },
  // General / Interpretive
  'DEF-GENERAL': {
    type: 'DEF',
    label: 'General Definitions Section',
    description: 'Main definitions section or cross-reference table',
    aliases: ['Definitions Section'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-INTERP': {
    type: 'DEF',
    label: 'Interpretation / Construction',
    description: 'Rules of interpretation (including, without limitation, etc.)',
    aliases: ['Interpretation', 'Rules of Construction'],
    frequency: 'universal',
    industries: [],
  },
  'DEF-MADE-AVAILABLE': {
    type: 'DEF',
    label: 'Made Available',
    description: 'What "made available" or "furnished" means (data room, SEC filings)',
    aliases: ['Made Available Definition', 'Furnished Definition'],
    frequency: 'common',
    industries: [],
  },
  'DEF-DISCLOSURELETTER': {
    type: 'DEF',
    label: 'Company Disclosure Letter',
    description: 'Scope and effect of the disclosure letter/schedules',
    aliases: ['Disclosure Letter', 'Disclosure Schedules', 'Company Disclosure Schedule'],
    frequency: 'common',
    industries: [],
  },

  // ── COV ─────────────────────────────────────────────────────────────────
  'COV-ACCESS': {
    type: 'COV',
    label: 'Access to Information; Confidentiality',
    description: 'Buyer\'s access to target\'s books, records, personnel',
    aliases: ['Access to Information', 'Books and Records Access'],
    frequency: 'universal',
    industries: [],
  },
  'COV-PROXY': {
    type: 'COV',
    label: 'Proxy Statement Preparation',
    description: 'Preparation and filing of proxy statement',
    aliases: ['Proxy Statement', 'Proxy Filing'],
    frequency: 'universal',
    industries: [],
  },
  'COV-MEETING': {
    type: 'COV',
    label: 'Stockholders Meeting',
    description: 'Obligation to hold and recommend at stockholder meeting',
    aliases: ['Stockholder Meeting', 'Shareholder Meeting', 'Company Meeting'],
    frequency: 'universal',
    industries: [],
  },
  'COV-PUBLICITY': {
    type: 'COV',
    label: 'Public Announcements; Disclosure',
    description: 'Coordination of public communications',
    aliases: ['Public Announcements', 'Press Releases', 'Publicity'],
    frequency: 'near-universal',
    industries: [],
  },
  'COV-INDEMN': {
    type: 'COV',
    label: 'Indemnification; D&O Insurance',
    description: 'Post-closing D&O indemnification and insurance tail',
    aliases: ['D&O Indemnification', 'D&O Insurance Tail', 'Director Indemnification'],
    frequency: 'near-universal',
    industries: [],
  },
  'COV-EMPLOYEE': {
    type: 'COV',
    label: 'Employee Matters; Benefits',
    description: 'Post-closing employee benefit obligations',
    aliases: ['Employee Matters', 'Post-Closing Employee Benefits', 'Employee Covenants'],
    frequency: 'near-universal',
    industries: [],
  },
  'COV-TAKEOVER': {
    type: 'COV',
    label: 'Takeover Laws',
    description: 'Obligation to prevent anti-takeover statutes from applying',
    aliases: ['Anti-Takeover Covenant', 'Section 203 Waiver'],
    frequency: 'common',
    industries: [],
  },
  'COV-NOTIFY': {
    type: 'COV',
    label: 'Notification of Certain Matters',
    description: 'Obligation to notify of material developments',
    aliases: ['Notification Covenant', 'Material Developments Notice'],
    frequency: 'common',
    industries: [],
  },
  'COV-LITNOTIFY': {
    type: 'COV',
    label: 'Stockholder / Transaction Litigation',
    description: 'Coordination on stockholder litigation',
    aliases: ['Transaction Litigation', 'Stockholder Litigation'],
    frequency: 'common',
    industries: [],
  },
  'COV-16B': {
    type: 'COV',
    label: 'Rule 16b-3 / Section 16 Matters',
    description: 'Section 16 exemption for insider transactions',
    aliases: ['Section 16', 'Rule 16b-3', 'Short-Swing Profit Exemption'],
    frequency: 'common',
    industries: [],
  },
  'COV-RESIGN': {
    type: 'COV',
    label: 'Director Resignations',
    description: 'Company director resignations at closing',
    aliases: ['Board Resignations', 'Director Resignations at Closing'],
    frequency: 'common',
    industries: [],
  },
  'COV-FINANCING': {
    type: 'COV',
    label: 'Financing; Financing Cooperation',
    description: 'Buyer financing and target\'s cooperation obligations',
    aliases: ['Financing Covenant', 'Financing Cooperation', 'Debt Financing'],
    frequency: 'common',
    industries: [],
  },
  'COV-DELIST': {
    type: 'COV',
    label: 'Stock Exchange Delisting; Deregistration',
    description: 'Post-closing delisting and deregistration',
    aliases: ['Delisting', 'Deregistration', 'SEC Deregistration'],
    frequency: 'common',
    industries: [],
  },
  'COV-LIST': {
    type: 'COV',
    label: 'Stock Exchange Listing',
    description: 'Listing of new shares (stock-for-stock)',
    aliases: ['Listing Covenant', 'Share Listing'],
    frequency: 'common',
    industries: [],
  },
  'COV-FURTHER': {
    type: 'COV',
    label: 'Further Assurances',
    description: 'General obligation to take further actions',
    aliases: ['Further Assurances', 'Further Actions'],
    frequency: 'common',
    industries: [],
  },
  'COV-SECREPORT': {
    type: 'COV',
    label: 'Post-Closing SEC Reports',
    description: 'Post-closing SEC reporting obligations',
    aliases: ['SEC Reporting', 'Post-Closing Reports'],
    frequency: 'common',
    industries: [],
  },
  'COV-TAXMATTERS': {
    type: 'COV',
    label: 'Tax Matters',
    description: 'Tax-related covenants and cooperation',
    aliases: ['Tax Covenants', 'Tax Cooperation'],
    frequency: 'common',
    industries: [],
  },
  'COV-DEBT': {
    type: 'COV',
    label: 'Treatment of Existing Indebtedness / Notes',
    description: 'Handling of target\'s existing debt',
    aliases: ['Debt Treatment', 'Notes Payoff', 'Existing Indebtedness'],
    frequency: 'common',
    industries: [],
  },
  'COV-MERGESUB': {
    type: 'COV',
    label: 'Merger Sub Compliance',
    description: 'Obligations regarding merger sub',
    aliases: ['Merger Sub Covenant', 'Merger Sub Obligations'],
    frequency: 'common',
    industries: [],
  },
  'COV-DIVIDEND': {
    type: 'COV',
    label: 'Coordination of Dividends',
    description: 'Coordination of dividend payments pre-closing',
    aliases: ['Dividend Coordination', 'Pre-Closing Dividends'],
    frequency: 'common',
    industries: [],
  },
  'COV-CONSENT': {
    type: 'COV',
    label: 'Delivery of Written Consents',
    description: 'Delivery of required consents',
    aliases: ['Written Consents', 'Consent Delivery'],
    frequency: 'common',
    industries: [],
  },
  'COV-PAYOFF': {
    type: 'COV',
    label: 'Payoff Letters',
    description: 'Delivery of payoff letters',
    aliases: ['Payoff Letters', 'Debt Payoff'],
    frequency: 'common',
    industries: [],
  },
  'COV-CVR': {
    type: 'COV',
    label: 'CVR Agreement',
    description: 'Contingent value rights agreement',
    aliases: ['Contingent Value Rights', 'CVR', 'Contingent Consideration'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },
  // Pharma-specific covenants (cross-check additions)
  'COV-FDACOMMS': {
    type: 'COV',
    label: 'FDA Communications',
    description: 'Coordination and notification regarding FDA communications, meetings, and submissions',
    aliases: ['FDA Communications Covenant', 'Regulatory Communications', 'FDA Meetings'],
    frequency: 'industry-specific',
    industries: ['pharma'],
  },

  // ── MISC ────────────────────────────────────────────────────────────────
  'MISC-SURVIVAL': {
    type: 'MISC',
    label: 'No Survival / Nonsurvival',
    description: 'Survival (or not) of representations post-closing',
    aliases: ['Nonsurvival', 'No Survival of Reps'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-NOTICES': {
    type: 'MISC',
    label: 'Notices',
    description: 'Notice addresses and mechanics',
    aliases: ['Notice Provisions', 'Notice Addresses'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-ENTIRE': {
    type: 'MISC',
    label: 'Entire Agreement',
    description: 'Integration / entire agreement clause',
    aliases: ['Integration Clause', 'Entire Agreement Clause'],
    frequency: 'near-universal',
    industries: [],
  },
  'MISC-GOVLAW': {
    type: 'MISC',
    label: 'Governing Law',
    description: 'Choice of governing law',
    aliases: ['Choice of Law', 'Applicable Law'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-JURISD': {
    type: 'MISC',
    label: 'Jurisdiction; Venue',
    description: 'Submission to jurisdiction and venue',
    aliases: ['Jurisdiction', 'Venue', 'Forum Selection'],
    frequency: 'common',
    industries: [],
  },
  'MISC-JURY': {
    type: 'MISC',
    label: 'Waiver of Jury Trial',
    description: 'Jury trial waiver',
    aliases: ['Jury Waiver', 'Waiver of Trial by Jury'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-ASSIGN': {
    type: 'MISC',
    label: 'Assignment; Successors',
    description: 'Assignment restrictions and successors',
    aliases: ['Assignment', 'Successors and Assigns'],
    frequency: 'near-universal',
    industries: [],
  },
  'MISC-SEVER': {
    type: 'MISC',
    label: 'Severability',
    description: 'Severability of invalid provisions',
    aliases: ['Severability Clause'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-COUNTER': {
    type: 'MISC',
    label: 'Counterparts',
    description: 'Execution in counterparts',
    aliases: ['Counterparts', 'Electronic Signatures'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-SPECIFIC': {
    type: 'MISC',
    label: 'Specific Performance; Enforcement',
    description: 'Right to specific performance',
    aliases: ['Specific Performance', 'Equitable Relief', 'Injunctive Relief'],
    frequency: 'universal',
    industries: [],
  },
  'MISC-THIRDPARTY': {
    type: 'MISC',
    label: 'Third-Party Beneficiaries',
    description: 'No third-party beneficiary rights (with exceptions)',
    aliases: ['No Third-Party Beneficiaries'],
    frequency: 'common',
    industries: [],
  },
  'MISC-AMEND': {
    type: 'MISC',
    label: 'Amendment; Modification',
    description: 'Process for amending the agreement',
    aliases: ['Amendment', 'Modification'],
    frequency: 'common',
    industries: [],
  },
  'MISC-WAIVER': {
    type: 'MISC',
    label: 'Waiver; Extension',
    description: 'Waiver mechanics',
    aliases: ['Waiver', 'Extension of Time'],
    frequency: 'common',
    industries: [],
  },
  'MISC-EXPENSES': {
    type: 'MISC',
    label: 'Expenses',
    description: 'General expense allocation (if separate from TERMF)',
    aliases: ['Fees and Expenses', 'Transaction Expenses'],
    frequency: 'common',
    industries: [],
  },
  'MISC-CONSTRUCT': {
    type: 'MISC',
    label: 'Rules of Construction; Interpretation',
    description: 'Interpretive provisions',
    aliases: ['Rules of Construction', 'Interpretation Clause'],
    frequency: 'common',
    industries: [],
  },
};

// ---------------------------------------------------------------------------
// 3. FEATURES — extractable features keyed by provision type
// ---------------------------------------------------------------------------

const FEATURES = {
  IOC: [
    {
      key: 'mainObligation',
      label: 'Main Obligation (one-sentence summary of what the sub-clause restricts or requires)',
      type: 'text',
    },
    {
      key: 'consentStandard',
      label: 'Consent Standard',
      type: 'enum',
      options: ['prior-written', 'not-unreasonably-withheld', 'sole-discretion'],
    },
    {
      key: 'dollarThreshold',
      label: 'Dollar Threshold',
      type: 'currency',
    },
    {
      key: 'permittedExceptions',
      label: 'Permitted Exceptions — ONLY include text that genuinely begins with "except", "other than", "provided that", or "notwithstanding". Do NOT include every sub-clause.',
      type: 'list',
    },
    {
      key: 'scheduleReference',
      label: 'Schedule Reference (e.g. "Section 4.1(b) of the Company Disclosure Letter")',
      type: 'text',
    },
    {
      key: 'crossReferences',
      label: 'Cross References (other sections/articles referenced)',
      type: 'list',
    },
    {
      key: 'ordinaryCourseCarveout',
      label: 'Ordinary Course Carve-out',
      type: 'boolean',
    },
    {
      key: 'requiredByLawCarveout',
      label: 'Required by Law Carve-out',
      type: 'boolean',
    },
    {
      key: 'pandemicCarveout',
      label: 'Pandemic / COVID Carve-out',
      type: 'boolean',
    },
    {
      key: 'effortsStandard',
      label: 'Efforts Standard',
      type: 'enum',
      options: ['commercially-reasonable', 'reasonable-best-efforts', 'best-efforts'],
    },
    {
      key: 'materialityQualifier',
      label: 'Materiality Qualifier',
      type: 'boolean',
    },
  ],

  'COND-M': [
    {
      key: 'mainCondition',
      label: 'Main Condition (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'bringDownStandard',
      label: 'Bring-Down Standard',
      type: 'enum',
      options: ['true-and-correct-in-all-respects', 'true-and-correct-in-all-material-respects', 'true-and-correct-except-MAE', 'true-and-correct-except-de-minimis'],
    },
    {
      key: 'tieredBringDown',
      label: 'Tiered Bring-Down (fundamental vs. other reps)',
      type: 'boolean',
    },
    {
      key: 'tiers',
      label: 'Tiers Breakdown (each tier as a string)',
      type: 'list',
    },
    {
      key: 'certificationRequired',
      label: 'Officer Certification Required',
      type: 'boolean',
    },
    {
      key: 'dollarThreshold',
      label: 'Dollar Threshold',
      type: 'currency',
    },
    {
      key: 'scheduleReference',
      label: 'Schedule Reference',
      type: 'text',
    },
  ],

  'COND-B': [
    {
      key: 'mainCondition',
      label: 'Main Condition (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'bringDownStandard',
      label: 'Bring-Down Standard',
      type: 'enum',
      options: ['true-and-correct-in-all-respects', 'true-and-correct-in-all-material-respects', 'true-and-correct-except-MAE', 'true-and-correct-except-de-minimis'],
    },
    {
      key: 'tieredBringDown',
      label: 'Tiered Bring-Down (fundamental vs. other reps)',
      type: 'boolean',
    },
    {
      key: 'tiers',
      label: 'Tiers Breakdown (each tier as a string)',
      type: 'list',
    },
    {
      key: 'certificationRequired',
      label: 'Officer Certification Required',
      type: 'boolean',
    },
    {
      key: 'maeConditionStandalone',
      label: 'MAE as Standalone Condition (vs. embedded in rep bring-down)',
      type: 'boolean',
    },
    {
      key: 'dollarThreshold',
      label: 'Dollar Threshold',
      type: 'currency',
    },
    {
      key: 'dissentingSharesThreshold',
      label: 'Dissenting Shares Threshold',
      type: 'percentage',
    },
    {
      key: 'scheduleReference',
      label: 'Schedule Reference',
      type: 'text',
    },
  ],

  'COND-S': [
    {
      key: 'mainCondition',
      label: 'Main Condition (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'bringDownStandard',
      label: 'Bring-Down Standard',
      type: 'enum',
      options: ['true-and-correct-in-all-respects', 'true-and-correct-in-all-material-respects', 'true-and-correct-except-MAE', 'true-and-correct-except-de-minimis'],
    },
    {
      key: 'tieredBringDown',
      label: 'Tiered Bring-Down (fundamental vs. other reps)',
      type: 'boolean',
    },
    {
      key: 'tiers',
      label: 'Tiers Breakdown (each tier as a string)',
      type: 'list',
    },
    {
      key: 'certificationRequired',
      label: 'Officer Certification Required',
      type: 'boolean',
    },
    {
      key: 'fundsCondition',
      label: 'Funds Availability as Condition',
      type: 'boolean',
    },
    {
      key: 'dollarThreshold',
      label: 'Dollar Threshold',
      type: 'currency',
    },
    {
      key: 'scheduleReference',
      label: 'Schedule Reference',
      type: 'text',
    },
  ],

  COND: [
    {
      key: 'mainCondition',
      label: 'Main Condition (one-sentence summary)',
      type: 'text',
    },
  ],

  NOSOL: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of this provision)',
      type: 'text',
    },
    {
      key: 'noticePeriod',
      label: 'Notice Period (hours)',
      type: 'duration',
    },
    {
      key: 'matchingPeriod',
      label: 'Matching Period (business days)',
      type: 'duration',
    },
    {
      key: 'goShopWindow',
      label: 'Go-Shop Window (calendar days)',
      type: 'duration',
    },
    {
      key: 'informationRights',
      label: 'Information Rights (bidder access to data room)',
      type: 'boolean',
    },
    {
      key: 'subsequentMatching',
      label: 'Subsequent Matching on Amendments',
      type: 'boolean',
    },
    {
      key: 'subsequentMatchingPeriod',
      label: 'Subsequent Matching Period (business days)',
      type: 'duration',
    },
    {
      key: 'fiduciaryOutStandard',
      label: 'Fiduciary Out Standard',
      type: 'enum',
      options: ['reasonably-likely-to-lead-to-superior', 'could-reasonably-be-expected-to-lead-to-superior', 'constitutes-or-could-lead-to-superior'],
    },
    {
      key: 'interveningEventProvision',
      label: 'Intervening Event Provision Exists',
      type: 'boolean',
    },
    {
      key: 'standstillWaiver',
      label: 'Standstill Waiver Permitted',
      type: 'boolean',
    },
    {
      key: 'dontAskDontWaive',
      label: 'Don\'t-Ask-Don\'t-Waive Provision',
      type: 'boolean',
    },
    {
      key: 'confidentialityRequired',
      label: 'Confidentiality Agreement Required for Information Access',
      type: 'boolean',
    },
    {
      key: 'superiorProposalPercentage',
      label: 'Superior Proposal Percentage Threshold',
      type: 'percentage',
    },
    {
      key: 'fiduciaryCarveoutThreshold',
      label: 'Fiduciary Carve-Out Threshold (the standard the board must meet to engage)',
      type: 'text',
    },
  ],

  ANTI: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of this provision)',
      type: 'text',
    },
    {
      key: 'effortsStandard',
      label: 'Efforts Standard',
      type: 'enum',
      options: ['best-efforts', 'reasonable-best-efforts', 'commercially-reasonable-efforts', 'reasonable-efforts'],
    },
    {
      key: 'hellOrHighWater',
      label: 'Hell-or-High-Water (no divestiture cap)',
      type: 'boolean',
    },
    {
      key: 'divestitureCap',
      label: 'Divestiture Cap (dollar or revenue threshold)',
      type: 'currency',
    },
    {
      key: 'divestitureCapDescription',
      label: 'Divestiture Cap Description',
      type: 'text',
    },
    {
      key: 'litigationObligation',
      label: 'Obligation to Litigate Against Regulators',
      type: 'enum',
      options: ['required', 'permitted-not-required', 'prohibited', 'silent'],
    },
    {
      key: 'filingDeadline',
      label: 'Filing Deadline (business days after signing)',
      type: 'duration',
    },
    {
      key: 'foreignFilingsRequired',
      label: 'Foreign Regulatory Filings Required',
      type: 'list',
    },
    {
      key: 'interimOperatingRestrictions',
      label: 'Interim Operating Restrictions During Review',
      type: 'boolean',
    },
    {
      key: 'pullAndRefileRight',
      label: 'Pull-and-Refile Right',
      type: 'boolean',
    },
    {
      key: 'burdensomConditionDefined',
      label: 'Burdensome Condition Defined',
      type: 'boolean',
    },
    {
      key: 'partyControlsStrategy',
      label: 'Party That Controls Regulatory Strategy',
      type: 'enum',
      options: ['buyer', 'target', 'mutual', 'silent'],
    },
  ],

  TERMF: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of the fee provision)',
      type: 'text',
    },
    {
      key: 'triggerEvents',
      label: 'Trigger Events (events that cause the fee to be payable)',
      type: 'list',
    },
    {
      key: 'feeAmount',
      label: 'Fee Amount (dollars)',
      type: 'currency',
    },
    {
      key: 'feePercentage',
      label: 'Fee as Percentage of Deal Value',
      type: 'percentage',
    },
    {
      key: 'reverseFeeAmount',
      label: 'Reverse Fee Amount (dollars)',
      type: 'currency',
    },
    {
      key: 'reverseFeePercentage',
      label: 'Reverse Fee as Percentage of Deal Value',
      type: 'percentage',
    },
    {
      key: 'tailPeriod',
      label: 'Tail Period (months)',
      type: 'duration',
    },
    {
      key: 'soleRemedy',
      label: 'Fee is Sole and Exclusive Remedy',
      type: 'boolean',
    },
    {
      key: 'willfulBreachException',
      label: 'Willful Breach Carve-out to Sole Remedy',
      type: 'boolean',
    },
    {
      key: 'expenseReimbursement',
      label: 'Expense Reimbursement Included',
      type: 'boolean',
    },
    {
      key: 'expenseReimbursementCap',
      label: 'Expense Reimbursement Cap',
      type: 'currency',
    },
    {
      key: 'nakedNoVoteFee',
      label: 'Naked No-Vote Fee (reduced fee if no competing proposal)',
      type: 'boolean',
    },
  ],

  TERMR: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'partyWhoCanTerminate',
      label: 'Party Who Can Terminate',
      type: 'enum',
      options: ['buyer', 'target', 'either', 'mutual'],
    },
    {
      key: 'terminationTriggers',
      label: 'Termination Triggers — the LIST of conditions that allow termination. Do NOT include exceptions / carve-outs to termination.',
      type: 'list',
    },
    {
      key: 'faultBasedExclusion',
      label: 'Fault-Based Exclusion (party at fault cannot invoke)',
      type: 'boolean',
    },
    {
      key: 'outsideDate',
      label: 'Outside Date',
      type: 'text',
    },
    {
      key: 'outsideDateMonths',
      label: 'Outside Date (months after signing)',
      type: 'duration',
    },
    {
      key: 'extensionAvailable',
      label: 'Extension of Outside Date Available',
      type: 'boolean',
    },
    {
      key: 'extensionPeriod',
      label: 'Extension Period (months)',
      type: 'duration',
    },
    {
      key: 'extensionTrigger',
      label: 'Extension Trigger',
      type: 'enum',
      options: ['automatic', 'at-option-of-either-party', 'at-option-of-one-party', 'regulatory-condition-only'],
    },
    {
      key: 'curePeriod',
      label: 'Cure Period for Breach (business days)',
      type: 'duration',
    },
    {
      key: 'superiorProposalTermination',
      label: 'Target Can Terminate for Superior Proposal',
      type: 'boolean',
    },
    {
      key: 'tickingFee',
      label: 'Ticking Fee / Reverse Ticking Fee',
      type: 'boolean',
    },
  ],

  DEF: [
    {
      key: 'mainConcept',
      label: 'Main Concept (short summary of the defined term)',
      type: 'text',
    },
    {
      key: 'canonicalTerm',
      label: 'Canonical Term (the quoted defined term as it appears in the agreement)',
      type: 'text',
    },
    {
      key: 'definitionText',
      label: 'Definition Text (the core definition body, excluding carve-outs)',
      type: 'text',
    },
    {
      key: 'crossReferences',
      label: 'Cross References (other defined terms or sections referenced)',
      type: 'list',
    },
    {
      key: 'carveOuts',
      label: 'Carve-Outs (for MAE — enumerated exceptions)',
      type: 'list',
    },
    {
      key: 'carveOutsList',
      label: 'MAE Carve-Outs List (deprecated alias for carveOuts)',
      type: 'list',
    },
    {
      key: 'disproportionateImpactClause',
      label: 'Disproportionate Impact Clause (text of the disproportionate-impact qualifier)',
      type: 'text',
    },
    {
      key: 'disproportionateImpact',
      label: 'Disproportionate Impact Qualifier',
      type: 'boolean',
    },
    {
      key: 'disproportionateImpactScope',
      label: 'Disproportionate Impact Scope (which carve-outs)',
      type: 'list',
    },
    {
      key: 'knowledgeStandard',
      label: 'Knowledge Standard',
      type: 'enum',
      options: ['actual-knowledge', 'constructive-knowledge', 'after-reasonable-inquiry', 'actual-knowledge-after-due-inquiry'],
    },
    {
      key: 'knowledgePersons',
      label: 'Knowledge Persons (named individuals or by title)',
      type: 'list',
    },
    {
      key: 'ordinaryCourseQualifier',
      label: 'Ordinary Course Qualifier',
      type: 'enum',
      options: ['ordinary-course-only', 'ordinary-course-consistent-with-past-practice', 'ordinary-course-consistent-in-all-material-respects'],
    },
    {
      key: 'willfulBreachDefinition',
      label: 'Willful Breach Defined',
      type: 'boolean',
    },
    {
      key: 'superiorProposalPercentage',
      label: 'Superior Proposal Percentage Threshold',
      type: 'percentage',
    },
    {
      key: 'acquisitionProposalPercentage',
      label: 'Acquisition Proposal Percentage Threshold',
      type: 'percentage',
    },
    {
      key: 'pandemicCarveout',
      label: 'Pandemic / COVID MAE Carve-Out',
      type: 'boolean',
    },
    {
      key: 'cyberSecurityCarveout',
      label: 'Cybersecurity Incident MAE Carve-Out',
      type: 'boolean',
    },
  ],

  STRUCT: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'mergerForm',
      label: 'Merger Form',
      type: 'enum',
      options: ['direct-merger', 'reverse-triangular', 'forward-triangular', 'two-step-tender'],
    },
    {
      key: 'survivingEntity',
      label: 'Surviving Entity',
      type: 'text',
    },
    {
      key: 'closingConditionsPrecedent',
      label: 'Closing Conditions Precedent Summary',
      type: 'text',
    },
  ],

  CONSID: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'considerationType',
      label: 'Consideration Type',
      type: 'enum',
      options: ['all-cash', 'all-stock', 'mixed-cash-and-stock', 'cash-with-cvr'],
    },
    {
      key: 'perShareAmount',
      label: 'Per Share Cash Amount',
      type: 'currency',
    },
    {
      key: 'exchangeRatio',
      label: 'Exchange Ratio (stock deals)',
      type: 'text',
    },
    {
      key: 'equityAwardTreatment',
      label: 'Equity Award Treatment Summary',
      type: 'text',
    },
    {
      key: 'appraisalRightsAvailable',
      label: 'Appraisal Rights Available',
      type: 'boolean',
    },
    {
      key: 'withholdingProvision',
      label: 'Withholding Provision Included',
      type: 'boolean',
    },
    {
      key: 'proration',
      label: 'Proration Mechanism (mixed deals)',
      type: 'boolean',
    },
  ],

  'REP-T': [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of the representation)',
      type: 'text',
    },
    {
      key: 'crossReferences',
      label: 'Cross References (other sections / defined terms / disclosure schedule citations)',
      type: 'list',
    },
    {
      key: 'materialityQualifier',
      label: 'Materiality Qualifier (double-materiality scrape)',
      type: 'boolean',
    },
    {
      key: 'knowledgeQualifier',
      label: 'Knowledge Qualifier Used',
      type: 'boolean',
    },
    {
      key: 'bringDownStandard',
      label: 'Applicable Bring-Down Standard',
      type: 'enum',
      options: ['all-respects', 'material-respects', 'MAE-standard', 'de-minimis'],
    },
    {
      key: 'scheduleReference',
      label: 'Disclosure Schedule Cross-Reference',
      type: 'text',
    },
    {
      key: 'survivalPeriod',
      label: 'Survival Period',
      type: 'duration',
    },
  ],

  'REP-B': [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of the representation)',
      type: 'text',
    },
    {
      key: 'crossReferences',
      label: 'Cross References (other sections / defined terms)',
      type: 'list',
    },
    {
      key: 'materialityQualifier',
      label: 'Materiality Qualifier',
      type: 'boolean',
    },
    {
      key: 'knowledgeQualifier',
      label: 'Knowledge Qualifier Used',
      type: 'boolean',
    },
    {
      key: 'bringDownStandard',
      label: 'Applicable Bring-Down Standard',
      type: 'enum',
      options: ['all-respects', 'material-respects', 'MAE-standard', 'de-minimis'],
    },
    {
      key: 'solvencyRepIncluded',
      label: 'Solvency Representation Included',
      type: 'boolean',
    },
    {
      key: 'financingRepIncluded',
      label: 'Financing / Sufficient Funds Rep Included',
      type: 'boolean',
    },
  ],

  COV: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary of the covenant)',
      type: 'text',
    },
    {
      key: 'accessScope',
      label: 'Access Scope',
      type: 'enum',
      options: ['broad-access', 'reasonable-access', 'limited-access'],
    },
    {
      key: 'indemnificationPeriod',
      label: 'D&O Indemnification Tail Period (years)',
      type: 'duration',
    },
    {
      key: 'employeeBenefitPeriod',
      label: 'Employee Benefit Continuation Period (months)',
      type: 'duration',
    },
    {
      key: 'financingCooperation',
      label: 'Financing Cooperation Required',
      type: 'boolean',
    },
    {
      key: 'cvrIncluded',
      label: 'CVR Agreement Included',
      type: 'boolean',
    },
  ],

  MISC: [
    {
      key: 'mainConcept',
      label: 'Main Concept (one-sentence summary)',
      type: 'text',
    },
    {
      key: 'governingLaw',
      label: 'Governing Law Jurisdiction',
      type: 'text',
    },
    {
      key: 'jurisdictionExclusive',
      label: 'Exclusive Jurisdiction',
      type: 'boolean',
    },
    {
      key: 'juryWaiver',
      label: 'Jury Trial Waiver',
      type: 'boolean',
    },
    {
      key: 'specificPerformance',
      label: 'Specific Performance Available',
      type: 'boolean',
    },
    {
      key: 'thirdPartyBeneficiaryExceptions',
      label: 'Third-Party Beneficiary Exceptions',
      type: 'list',
    },
  ],
};

// ---------------------------------------------------------------------------
// Alias lookup index — built once at require time
// ---------------------------------------------------------------------------

const _aliasIndex = {};
for (const [code, entry] of Object.entries(CODES)) {
  if (entry.aliases) {
    for (const alias of entry.aliases) {
      _aliasIndex[alias.toLowerCase()] = code;
    }
  }
}

// ---------------------------------------------------------------------------
// Type lookup index
// ---------------------------------------------------------------------------

const _typeIndex = {};
for (const t of PROVISION_TYPES) {
  _typeIndex[t.key] = t;
}

// ---------------------------------------------------------------------------
// 4. Helper functions
// ---------------------------------------------------------------------------

/**
 * Returns an array of code entries for a given provision type key.
 * Each entry is { code, ...codeData }.
 */
function getCodesForType(typeKey) {
  const results = [];
  for (const [code, entry] of Object.entries(CODES)) {
    if (entry.type === typeKey) {
      results.push({ code, ...entry });
    }
  }
  return results;
}

/**
 * Returns true if the given code string exists in the rubric.
 */
function isValidCode(code) {
  return Object.prototype.hasOwnProperty.call(CODES, code);
}

/**
 * Finds the canonical code for a given alias string (case-insensitive).
 * Returns the code string or null.
 */
function findCodeByAlias(alias) {
  if (!alias) return null;
  // Exact code match first
  if (isValidCode(alias)) return alias;
  // Alias lookup (case-insensitive)
  return _aliasIndex[alias.toLowerCase()] || null;
}

/**
 * Returns the human-readable label for a provision type key.
 */
function getTypeLabel(typeKey) {
  const t = _typeIndex[typeKey];
  return t ? t.label : null;
}

/**
 * Returns the feature definitions array for a provision type key.
 * Returns an empty array if the type has no features defined.
 */
function getFeaturesForType(typeKey) {
  return FEATURES[typeKey] || [];
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  PROVISION_TYPES,
  CODES,
  FEATURES,
  getCodesForType,
  isValidCode,
  findCodeByAlias,
  getTypeLabel,
  getFeaturesForType,
};
